### ISSUE TITLE
add binarysearch.io contests

### ISSUE THREAD

**Issue by jaewie** [aropan/clist#105]
Hi there, https://binarysearch.io is a site similar to Leetcode for preparing for interviews. We have rated contests every Saturday at 6:00pm UTC and an unrated contest every Wednesday at 3:00am UTC.

Some past weekly contests (chats are disabled during all contests)
- [Weekly Contest 15](https://binarysearch.io/room/Weekly-Contest-15-23770)
- [Weekly Contest 14](https://binarysearch.io/room/Weekly-Contest-14-22601)
- [Weekly Contest 13](https://binarysearch.io/room/Weekly-Contest-13-21221)

Some past educational contests:
- [Educational Contest 6](https://binarysearch.io/room/Educational-Contest-6-24957)
- [Educational Contest 5](https://binarysearch.io/room/Educational-Contest-5-23771)
- [Educational Contest 4](https://binarysearch.io/room/Educational-Contest-4-22602)

If you're okay to add the site, could you describe what format I should provide my API? I currently have an endpoint [here](https://binarysearch.io/api/contests) which lists the upcoming/previous contests.

**Comment by aropan** [comment]
Please add `starting` to all events and set not null value.

**Comment by aropan** [comment]
Added `Weekly Contest 16` only.

**Comment by jaewie** [comment]
Thanks @aropan, sounds good. I added `starting` to all events.

**Comment by aropan** [comment]
Great. All past contests have been added and future contests will be added. https://clist.by/resource/binarysearch.io/

**Comment by aropan** [comment]
@jaewie do you have api for contest leaderboard? Like this https://codeforces.com/apiHelp/methods#contest.standings.
