### ISSUE TITLE
Repeatedly sends email for same contest.

### ISSUE THREAD

**Issue by bqi343** [aropan/clist#106]
Was fine for other contests ...

<img width="975" alt="Screen Shot 2020-07-22 at 12 04 13 PM" src="https://user-images.githubusercontent.com/21228024/88202073-57a50200-cc16-11ea-803f-397d31270888.png">

**Comment by aropan** [comment]
Thanks. I think I fixed it.

**Comment by aropan** [comment]
I fixed it. Let me know if there are any problems.
