### ISSUE TITLE
Time line for the current time in the calendar 

### ISSUE THREAD

**Issue by sharath29** [aropan/clist#108]
It would be a good feature where the current time is shown as a line on the calendar view when week tab is chosen

**Comment by aropan** [comment]
![image](https://user-images.githubusercontent.com/1968460/95640111-db4aee00-0aa3-11eb-8937-cee161f2314f.png)
Like this?

**Comment by sharath29** [comment]
yess!

**Comment by aropan** [comment]
Fixed.
