### ISSUE TITLE
Changing handle in the middle of SNSS

### ISSUE THREAD

**Issue by maksim1744** [aropan/clist#109]
I changed my handle in yandex from "Максим Гороховский" to "Maksim1744" at some point during the [snarknews summer series 2020](http://snss2020.snarknews.info/). Now I have two handles in [clist scoreboard](https://clist.by/standings/snarknews-summer-series-2020-21527010/) -- one for rounds 1-4, and another for round 5. In an [official scoreboard](http://snss2020.snarknews.info/index.cgi?data=snss20/global&menu=index&head=index&mod=snss20&class=snss20) this handles are merged together (probably because they know my id inside yandex or something). So, maybe it is worth parsing official scoreboard? If not, can you please just merge my two handles together manually? :)

Also, I guess you parse standings from each round and then merge same handles. Will it break if two people have same handles? Just curious

**Comment by aropan** [comment]
I generate (not parse) final scoreboard to do it right after the round (after round standings open).

You can add one more account to your clist profile and these accounts are merged.

Yes, if more than one accounts have same handle then standings will be broken.

**Comment by aropan** [comment]
But there are still problems.

**Comment by aropan** [comment]
Fixed what I noticed.
