### ISSUE TITLE
Add to Google Calendar (enhancement)

### ISSUE THREAD

**Issue by ishan-agarwal** [aropan/clist#110]
An add to google calendar option would be wonderful if maybe the user signs up using google.

**Comment by aropan** [comment]
You can import some event to your calendar:
* go to https://clist.by/settings/preferences/;
* select calendar import:
![image](https://user-images.githubusercontent.com/1968460/95639575-a0e05180-0aa1-11eb-96f2-a2cc9d399f10.png)
* click calendar icon in list:
![image](https://user-images.githubusercontent.com/1968460/95639847-b4d88300-0aa2-11eb-8bb9-993f34082894.png)
or in calendar:
![image](https://user-images.githubusercontent.com/1968460/95639852-bbff9100-0aa2-11eb-8830-3c908e5329d1.png)

**Comment by aropan** [comment]
Also you can import full future calendar from each resource:
* open https://dev.clist.by/resources/
* click calendar required resource:
![image](https://user-images.githubusercontent.com/1968460/95639929-054fe080-0aa3-11eb-85f3-3718001eed48.png)
* add to your calendar:
![image](https://user-images.githubusercontent.com/1968460/95639940-13056600-0aa3-11eb-8e49-02204df60910.png)

**Comment by ishan-agarwal** [comment]
Ohhh,
