### ISSUE TITLE
Calendar of COCI is not updated

### ISSUE THREAD

**Issue by prprprpony** [aropan/clist#112]
You can see COCI 2020/2021 contest 1 ~ 3 in the [COCI page of clist](https://clist.by/resource/hsin.hr/coci/) but not in the [google calendar](https://calendar.google.com/calendar/embed?src=hk9m77jqcqghv827jng8av8b40@group.calendar.google.com)

**Comment by aropan** [comment]
Fixed. There was a problem with get all google calendars.
c47305daa0483e0179b43dcea3e6e05c2b648db3
