### ISSUE TITLE
Proposal for improving print form of "Coder's rating"

### ISSUE THREAD

**Issue by RakhmedovRS** [aropan/clist#115]
Have a good day.
If you try to print the page "Coder's rating" you will see that it looks a bit messy.
![image](https://user-images.githubusercontent.com/25452084/102808411-564c5100-43d1-11eb-828e-1432e4c67859.png)
Thanks in advance

**Comment by aropan** [comment]
Done. Check it.

![image](https://user-images.githubusercontent.com/1968460/103556034-34b79300-4ec2-11eb-95de-15fbda6c9424.png)

**Comment by RakhmedovRS** [comment]
@aropan Nice. Now it's much better now. I think I can close the issue. Thanks
