### ISSUE TITLE
Need Personalized different "filtered Long Calender"

### ISSUE THREAD

**Issue by grg124** [aropan/clist#116]
Calender in which like codechef 
have long and short contests.
Short contests filtered and having option to add them to Google calender.
And That too applicable for all Sites (Codechef , hackerearth, Hackerrank).

Event based option is more best.

**Comment by aropan** [comment]
You can to set filters https://clist.by/settings/filters/. Then you can to select filter on calendar page:
![image](https://user-images.githubusercontent.com/1968460/103448163-969bb100-4ca6-11eb-96d5-1312e525a931.png)

**Comment by aropan** [comment]
If the issue persists, please let me know.
