### ISSUE TITLE
Bug: Contest showing in calendar, but not showing in list or api response

### ISSUE THREAD

**Issue by Zeronfinity** [aropan/clist#119]
Contest name: 2020 NA Regionals Practice Contest 5
Link: https://open.kattis.com/contests/nar20practice5

This contest was showing in API response at first, but no longer showing in API response or in list mode of the website.
But it's still showing in calendar.

_Screenshot of contest missing in list mode_
![list](https://user-images.githubusercontent.com/34229687/104818652-21f27600-5853-11eb-8d15-57cb7c5163b0.PNG)

_Screenshot of contest in calendar mode_
![calendar](https://user-images.githubusercontent.com/34229687/104818654-23bc3980-5853-11eb-988a-b21a96bf02a2.PNG)

The contest is missing now in [this API response](https://clist.by:443/api/v1/contest/?start__gt=2021-01-16T00%3A00%3A00&start__lt=2021-01-18T00%3A00%3A00&order_by=start) too

**Comment by aropan** [comment]
I see this event started at 6 pm UTC on January 15 in the calendar. The event was past when you got the list and the api. There is the event start at 6 pm UTC on January 16 in the DB. I think the event was rescheduled. Add a screenshot from an original resource next time, please. Also, you can check the [page](https://legacy.clist.by/logs/update/).
