### ISSUE TITLE
DPhi ML Contests on Clist

### ISSUE THREAD

**Issue by chanukyapatnaik** [aropan/clist#120]
Hi Team, 

We at DPhi are a global community of Data Scientists, started with a vision to build Data Culture and Democratize Data Science Learning. We regularly conduct ML/DL education challenges. Could you please list down so that clist community can benefit from it. Our recent edition of Data Sprint is listed here: https://dphi.tech/practice/challenge/58
Let us know if you may need any other information. Many thanks!

**Comment by aropan** [comment]
Add start time to events, please. Also, end time to past events.

**Comment by aropan** [comment]
Added.
