### ISSUE TITLE
Can Reply Code Challenge be listed on Clist?

### ISSUE THREAD

**Issue by EdoVanja** [aropan/clist#124]
Hello,
I'm writing from Reply, the digital consulting company.
On 11th March from 16.30 to 20.30 PM CET, we'll have the free Reply Code Challenge, [Teen](https://challenges.reply.com/tamtamy/challenges/category/coding_teen#home) and [Standard Edition](https://challenges.reply.com/tamtamy/challenges/category/coding#home) .
Could the Challenge be listed on Clist?
Thanks,
Edoardo
Reply Challenges Team

**Comment by aropan** [comment]
Done.
