### ISSUE TITLE
Codechef Div3 contest parsing doesn't work

### ISSUE THREAD

**Issue by idemidov** [aropan/clist#125]
CodeChef recently introduced Div3 contests.

I've taken part in one of them - the rating change is reflected on the CodeChef website but not on CList.
<img width="614" alt="Screenshot 2021-03-01 at 12 25 58" src="https://user-images.githubusercontent.com/15875323/109477706-69426800-7a89-11eb-8f97-3c69907acc51.png">
<img width="1593" alt="Screenshot 2021-03-01 at 12 26 06" src="https://user-images.githubusercontent.com/15875323/109477712-6a739500-7a89-11eb-832b-39c156852bd8.png">

**Comment by aropan** [comment]
Fixed. Thank you for informing me.
