### ISSUE TITLE
Add Humblefool Cup [Topcoder]

### ISSUE THREAD

**Issue by aryanc403** [aropan/clist#128]
https://codeforces.com/blog/entry/88726
It's an annual topcoder event with rated prelims and finals.

**Comment by aropan** [comment]
Passed.

**Comment by aryanc403** [comment]
I'm not sure what do you mean by passed. Does this mean you aren't adding it since it's over?     
Topcoder sponsors it every year. 
https://www.topcoder.com/2021-humblefool-cup/
https://www.topcoder.com/2020-humblefool-cup/
https://www.topcoder.com/2019-humblefool-cup/

This year's prelims are over. The Final is yet to be scheduled. Clist also offers post-contest tools not just a calendar before the contest. The reason I created this issue was this contest's standing wasn't present here https://clist.by/standings/ . I explicitly wanted to see a country filtered rank list to look at the potential list of finalists. This issue being closed doesn't help me with that.

Also, I'm assuming that clist parses this list from the topcoder calender. The issue being closed would mean finals would also be ignored. Once its added it will be added automatically every year.

**Comment by aropan** [comment]
Clist parses round statistics automatically when available on https://www.topcoder.com/tc?module=MatchList. The statistics are already there. Also, you can find standings previous prelims by [search](https://clist.by/standings/?search=topcoder+%26%26+HF+%7C%7C+Humblefool+%7C%7C+Humbleool).
