### ISSUE TITLE
Add LightOJ contests on clist

### ISSUE THREAD

**Issue by Zeronfinity** [aropan/clist#134]
[LightOJ](https://lightoj.com/home) is an online judge with many high-quality competitive programming problems. Although the OJ was created around 2011, recently they have brought out a new version that may host many contests in the future (one scheduled today for example).

The contests are publicly listed at [https://lightoj.com/contests](https://lightoj.com/contests). I also talked with them and found an API to get the data: [https://lightoj.com/api/v1/contests?page=1&contestType=currentOrUpcoming](https://lightoj.com/api/v1/contests?page=1&contestType=currentOrUpcoming)

Note that this API keeps all contests, even those created by any user. They plan on making a separate API for featured contests as well (i.e. contests arranged by LOJ itself). Kind of like CF contests and CF Gym contests.

**Comment by aropan** [comment]
Added. Lets me know when they add API to get contest results.
