### ISSUE TITLE
Codechef Graph & Rating Issue

### ISSUE THREAD

**Issue by sharmaumang001** [aropan/clist#135]
The website is not being able to fetch the data of Codechef -- Starters (held on 28-03-2021)

Not even showing the data on a graph. Also my rating increased in on of the contest but it is showing a decrease in the graph 

Check my profiles here : [Clist](https://clist.by/coder/sharmaumang001/) ,  [Codechef](https://www.codechef.com/users/sharmaumang001/)

**Comment by aropan** [comment]
Fixed. Other account ratings will be updated shortly. 
Thanks for the response.
