### ISSUE TITLE
Leetcode rating stopped updating

### ISSUE THREAD

**Issue by ctang131** [aropan/clist#137]
For leetcode weekly 234/235 and biweekly contest, 49 it stopped updating. However, leetcode website has the newly updated data.

**Comment by beginner789** [comment]
It seems that this issue has been fixed. Rating has been updated up to weekly 236.

**Comment by ctang131** [comment]
<img width="332" alt="Screen Shot 2021-04-19 at 2 33 09 PM" src="https://user-images.githubusercontent.com/56929653/115191570-324d1200-a11c-11eb-9f25-4fc88cd33dc9.png">
My rating graph still stays at weekly contest 231.

**Comment by ctang131** [comment]
Thanks, now it's fine.

**Comment by kumasento** [comment]
Has this issue resolved for Biweekly contests as well? Mine results only show up to Biweekly Contest 47, March 6.

**Comment by aropan** [comment]
It should be works now.
