### ISSUE TITLE
Cooperation in Organizing Machine Learning Competition

### ISSUE THREAD

**Issue by AliOsm** [aropan/clist#138]
Hello @aropan, your efforts in creating CLIST are amazing!
We are working on organizing a machine learning competition based on source codes.
Previously, we managed to collect 100K source codes from CodeForces paired with their users and organized a machine learning competition based on the data and it was a successful competition, you can see it from [here](https://sites.google.com/view/ai-soco-2020).
Currently, we are trying to collect as much data as we can (data here means source codes) to organize a new competition that tries to solve more complex and real-world problem.
I found that your website is crawling source codes from multiple online judges and I think we can cooperate to collect and organize the competiton.
Please, let me know if you are interested to elaborate more information, or we can setup a quick meeting to discuss.
Thanks!

**Comment by aropan** [comment]
Emailed you.
