### ISSUE TITLE
Add option of friends/lists by which we can filter standings

### ISSUE THREAD

**Issue by iampjeetsingh** [aropan/clist#142]
Since, we can see the standings of contests directly on clist.
There should be an option similar to Lists on Codeforces or Set on CodeChef by the help of which we should be able to filter standings of contests.
We should be able to add people into Lists/Set either by their clist username or by entering their usernames on various websites manually.

**Comment by aropan** [comment]
Done. Check to create a list here https://clist.by/settings/lists/. And filter on a standings page.

**Comment by iampjeetsingh** [comment]
It's working great
