### ISSUE TITLE
Add contests under PrepBytes MyCode Contests (mycode.prepbytes.com/contest) 

### ISSUE THREAD

**Issue by Git-Harshit** [aropan/clist#144]
This website for [PrepBytes MyCode Contests](https://mycode.prepbytes.com/contest) offers contests at regular intervals, that are free and open for all to participate in. This sub-site platform is relatively new, and isn't a lot popular due to which I have seen limited competition here as of now. However, I believe these contests are up to the mark and follow a good standard of problem set that is worth trying out. 

@aropan Please see to it, and add its contests to the listing of clist.by if you also agree on the point that these contests can be added up in your one-stop collective listing of all open competitive contests.

**Comment by aropan** [comment]
Done. https://clist.by/resource/mycode.prepbytes.com/
