### ISSUE TITLE
Unable to fetch handles for some of the resources.

### ISSUE THREAD

**Issue by aayushbest** [aropan/clist#153]
Hi Community,
I am unable to fetch my handles for some of the resources like projecteuler.net, toph.co etc in settings>Accounts.
Even I have my account active to those website.
Need help with that!
Thanks in advance.

**Comment by aropan** [comment]
You can add your account only after you will get into the results. It is mean you should be in top 100 for some problem for projecteuler resource. Is this condition satisfied?

**Comment by aayushbest** [comment]
It is not satisfied for ProjectEuler, but there are also others where I get account not found error such as Facebook Hackercup, Toph,co and binarysearch

**Comment by aropan** [comment]
Can you post your accounts here and I check them?

**Comment by aayushbest** [comment]
Hi,
Sorry for late response.
Here are the list of accounts where I get 'No account found' error:

1. acm.timus.ru -  Aayush Shrivastava
2. Facebook Hackercup - Aayush Shrivastava(aayushbest)
3. usaco.org - username:aayushbest / email: thebest1@live.in
4. codinggame.com - aayushbest/thebest1@live.in
5. toph.co - aayushbest
6. open.kattis.com - aayushbest
7. binarysearch.com - aayushbest
8. tlx.toki.id - aayushbest
9. csacademy.com - aayushbest
10. contest.bioinf.me - aayushbest/thebest1@live.in

**Comment by aropan** [comment]
@aayushbest As I wrote above _"...You can add your account only after you will get into the results..."_. Do you have a missing account that participated contest in a resource?

**Comment by aayushbest** [comment]
Hi I understood your point. And no other resource account is missing. You are doing great work. I will also like contribute to it as well :).
