### ISSUE TITLE
New coding site 

### ISSUE THREAD

**Issue by moein-yoo** [aropan/clist#155]
Hello, Hope you good days with no Covid .
I want to say that Iranian have site --> https://quera.ir
that is coding site which is so popular between us and mostly use it.
It has around 6000 coder signed up and mostly we use it for Informatic Olympiad.
But unfortunately it is in Persian.
Hope the bests.
Moein Yousefinia.

**Comment by aropan** [comment]
Do you know how to select algorithm contests only?

**Comment by aropan** [comment]
Hi. I think this resource will be useful when will be added English version. Let me know when it will be. Thanks.
