### ISSUE TITLE
feature request in statistics route

### ISSUE THREAD

**Issue by iampjeetsingh** [aropan/clist#157]
It would be great if statistics route supports these features
- Penality Time
- Performance (AtCoder)
- Problemwise data like points, penality, and number of wrong submissions (Should be off by default)

**Comment by aropan** [comment]
I added `with_more_fields` param for the first:
![image](https://user-images.githubusercontent.com/1968460/127755524-f4a7db75-8477-404c-829b-92ed73e275aa.png)
And `with_problems` param for last:
![image](https://user-images.githubusercontent.com/1968460/127755528-f3475395-1f73-48bc-82fc-2acd518d9a62.png)

**Comment by iampjeetsingh** [comment]
Thanks for the features.

Also, this contest is not yet parsed
https://codedrills.io/contests/icpc-amritapuri-2020-mock-round

**Comment by aropan** [comment]
Fixed https://clist.by/standings/icpc-amritapuri-2020-mock-round-28820744/.

**Comment by iampjeetsingh** [comment]
Currently, the problem dictionary only contains the problems which the user has attempted.
Could you provide some way to know how many problems the contest had?
Maybe you can add it to the contest route.

**Comment by aropan** [comment]
Done. https://clist.by/api/v2/contest/?with_problems=true&id=23072978&format=json:

![image](https://user-images.githubusercontent.com/1968460/128615210-45a92dfc-b001-42ae-86e2-3a3b825fa5ca.png)

**Comment by iampjeetsingh** [comment]
Thanks :)

**Comment by iampjeetsingh** [comment]
When I tried to access statistics with_problems for the contest `23072978`, the api responded with this error
```
{
  "error_message": "'list' object has no attribute 'lower'"
}
```

**Comment by aropan** [comment]
Fixed.
