### ISSUE TITLE
Kattis "Rating"s

### ISSUE THREAD

**Issue by madprogramer** [aropan/clist#164]
I noticed that [Kattis](
https://open.kattis.com/ranklist) is listed as `No Ratings` on the [Resources](https://clist.by/resources/) page. 

This is partially true, but partially false. Kattis does have a [Ranking system]( https://open.kattis.com/ranklist), but it's not based on contest, [rather all-time problems solved](https://open.kattis.com/help/ranklist#score). Each contest is treated as an isolated event, in the general ranking; but ex. 10 problems solved in a competition will contribute to the global ranking. To my knowledge, it's not possible to fall in ranking, unless other users pass you.

**Comment by aropan** [comment]
I added rating to Kattis resource. And configured a small period (50 days) to refresh the user's stats.

**Comment by aropan** [comment]
And added colors at my discretion.

**Comment by madprogramer** [comment]
Nice!
