### ISSUE TITLE
[Bug] Codechef contests not up to date

### ISSUE THREAD

**Issue by runxuanjiang** [aropan/clist#167]
I noticed that some CodeChef contests are not showing up on clist.by. For example, as of today (9/24/2021) the upcoming contests page on Codechef (https://www.codechef.com/contests/?itm_medium=navmenu&itm_campaign=allcontests) includes:

September Lunchtime 2021 (Sep 25 2021) (https://www.codechef.com/LTIME100)
Starters 13 (Sep 26 2021) (https://www.codechef.com/START13?itm_campaign=contest_listing)
Starters 14 (Sep 29 2021) (https://www.codechef.com/START14?itm_campaign=contest_listing)

However neither of these contests are listed on clist.by.

**Comment by aropan** [comment]
Fixed. Thanks for your notice.
