### ISSUE TITLE
DMOJ rating system received an update

### ISSUE THREAD

**Issue by int-y1** [aropan/clist#168]
DMOJ has moved to a different rating system, as described in [their blog post](https://dmoj.ca/post/206-ratings-migrated-to-elo-mmr). As a result, https://clist.by/resource/dmoj.ca/ needs an update too.

- [x] Update the rating cutoffs.
- [x] Refresh all the ratings. For example, in the "Top rating" list, REEmark has a rating of 2428, but the new rating system revised it to 2974.

**Comment by aropan** [comment]
Done. Check it, please.
