### ISSUE TITLE
Show total participants for each contest on profile page

### ISSUE THREAD

**Issue by Naranbayar** [aropan/clist#169]
How about showing total number of participants on coder profile page ?

Only showing "Rank" doesn't seem accurate enough for showing how well the coder performed for certain contest if we don't know how many contestants participated.

**Comment by aropan** [comment]
I added it by visual representation:
![image](https://user-images.githubusercontent.com/1968460/139561726-5194cbc0-6860-40e5-8ba2-c67cfab9ff0a.png)

**Comment by Naranbayar** [comment]
Looks great! Thanks @aropan
