### ISSUE TITLE
Support contests on Leetcode-CN?

### ISSUE THREAD

**Issue by hzfmer** [aropan/clist#170]
I found this website very cool, even for not strictly competitive programmers (e.g. Leetcode users).

I was wondering if it is possible to support "leetcode-CN" (https://leetcode-cn.com/contest/) as well?
Weekly/Biweekly contests on Leetcode.com are already included, but there are a number of people using leetcode-CN for the same contests. I guess adding "leetcode-CN" should be similar with "leetcode.com", thus perhaps not very complicated.

Thanks!

**Comment by aropan** [comment]
I did it. Isn't that supported?

I see lucifer1005 on https://clist.by/standings/weekly-contest-269-31367890/:

![image](https://user-images.githubusercontent.com/1968460/143766916-0b408675-c782-4575-802e-0414732e9a24.png)

open profile https://clist.by/account/lucifer1005/resource/leetcode.com/ and see URL to -cn:

![image](https://user-images.githubusercontent.com/1968460/143766981-c38cb318-e330-485b-bec3-9d44bd6b6c76.png)

Can you recheck it, please?

**Comment by hzfmer** [comment]
My bad. I didn't realize this. Thank you for this helpful tool!
