### ISSUE TITLE
Add sort-me.org support

### ISSUE THREAD

**Issue by sadfun** [aropan/clist#173]
Hi! It would be great to to add new, fast-growing competitive programming website: [sort-me.org](https://sort-me.org).
These guys hold Sort Me Round with unique tasks every month.

Also it's very easy to connect Sort Me: they have APIs for clist.by metrics, such as https://api.sort-me.org/getUsersCount and https://api.sort-me.org/getUpcomingContests.

**Comment by aropan** [comment]
Hi. Great resource, thanks. Can you add duration or end of contest to https://api.sort-me.org/getUpcomingContests?

**Comment by sadfun** [comment]
Sure! Added `ends` field.

**Comment by aropan** [comment]
[Done](https://clist.by/resource/sort-me.org/).

**Comment by sadfun** [comment]
Thank you very much :)
