### ISSUE TITLE
Atcoder upsolving not showing!

### ISSUE THREAD

**Issue by Frdhsn** [aropan/clist#174]
Despite upsolving the problems, at atcoder, the cyan color is not showing because I got one wrong answer in that problem during upsolving. Please fix this. Thanks.

**Comment by aropan** [comment]
What is the contest?

**Comment by Frdhsn** [comment]
AtCoder Beginner Contest 230 [https://atcoder.jp/contests/abc230/]

**Comment by aropan** [comment]
I think I fixed the bug. 🙂

**Comment by Frdhsn** [comment]
Yes, it's fixed. Thanks.
