### ISSUE TITLE
CodeForces handle change creates new account

### ISSUE THREAD

**Issue by nskybytskyi** [aropan/clist#175]
On CodeForces, users can change their handle once a year, during winter holidays. This change is not handled properly by clist.

The expected behavior is to merge the accounts automatically, or at least provide users with an option to do so manually. Such a merge can be verified automatically as CodeForces sets up a redirect from `/profile/{old_handle}` to `/profile/{new_handle}`.

Instead, a new record is created for the new username. This is, of course, confusing and undesired, as users cannot see both participation records in the same place. One example is https://clist.by/versus/Sky_Nik/vs/cf:nskybytskyi/

**Comment by aropan** [comment]
Yeap. I know about it. There is a mechanism to merge accounts on clist. But it works when an old account updates (it happens after participating contest or a long time after this). I will add a button to do it.

**Comment by aropan** [comment]
Fixed.

I added more intensive updating (also auto merging) coder's accounts on New Year's days. Also, I added to update account on add or remove from profile.
