### ISSUE TITLE
Wrong rounding in LeetCode rating

### ISSUE THREAD

**Issue by nskybytskyi** [aropan/clist#177]
LeetCode rating appears to be a real value instead of an integer one. One example service that backs up this assertion is [lcpredictor](https://lcpredictor.herokuapp.com/)

It appears that clist rounds LeetCode rating wrong: 
- [clist](https://clist.by/account/nskybytskyi/resource/leetcode.com/) says that my rounded rating is 2700
- [LeetCode](https://leetcode.com/nskybytskyi/) says that my rounded rating is 2701.
- [lcpredictor](https://lcpredictor.herokuapp.com/contest/weekly-contest-276/ranking/5?country=ALL) says that my actual rating is around 2700.56.

I, therefore, conclude that LeetCode rounds real-valued rating to the closest integer, and clist rounds it down. Please let me know if my assumption is correct or if more examples of wrong rounding are necessary.

**Comment by nskybytskyi** [comment]
As a matter of fact, your rating after Biweekly 69 😏 was wrong: 3023 on clist and 3024 on leetcode

**Comment by aropan** [comment]
Fixed. Thanks.

**Comment by aropan** [comment]
Started updating.
