### ISSUE TITLE
Feature Request: Add problem difficulty to problems

### ISSUE THREAD

**Issue by l3456** [aropan/clist#179]
I think it would be really cool to have problem difficulty somehow shown directly in clist.
For example, there's this site for atcoder: https://kenkoooo.com/atcoder#/table/

**Comment by aropan** [comment]
Done
https://clist.by/problems/

**Comment by aropan** [comment]
Resources with problems ratings

![image](https://user-images.githubusercontent.com/1968460/168488905-e6bccac2-cc5c-40f9-a717-3026dc2d2b5a.png)

**Comment by aropan** [comment]
And a little bit examples [here](https://t.me/clistbynews/41).

**Comment by l3456** [comment]
Awesome thanks!!
