### ISSUE TITLE
AtCoder Algorithm vs. Heuristic Ratings

### ISSUE THREAD

**Issue by bucketpotato01** [aropan/clist#181]
Currently, the site doesn't seem to differentiate between the different kinds of contests on AtCoder and tries to combine the two distinct rating plots into one.
<img width="154" alt="Screen Shot 2022-03-06 at 10 35 22 PM" src="https://user-images.githubusercontent.com/67671582/156980361-972bf8ee-6cde-4f26-a0e2-2f5b2e3b89aa.png">

**Comment by aropan** [comment]
I think I fixed it. Check https://clist.by/coder/BucketPotato/.

**Comment by bucketpotato01** [comment]
Thanks, looks good now
