### ISSUE TITLE
Google Kick Start Rank need to be updated

### ISSUE THREAD

**Issue by nevikw39** [aropan/clist#183]
Hello,

I found that my rank in Google Kick Start 2022 Round A was promoted a bit recently.

Right after the contest, the scoreboard was _in review_ for a while. And now, it was _finalized_. So it seemed that Google had disqualified some contestants.

Therefore, please update the rank of Google Kick Start 2022 Round A.

Thanks.

**Comment by aropan** [comment]
Done.

**Comment by nevikw39** [comment]
Thanks. This site is amazing.
