### ISSUE TITLE
Leetcode Ratings Are Not Updated

### ISSUE THREAD

**Issue by sdogsq** [aropan/clist#184]
Leetcode ratings have not been updated for quite a long time.
As for me:
- https://clist.by/account/sdogsq/resource/leetcode.com/
And some other random examples:
- https://clist.by/account/pku_erutan/resource/leetcode.com/
- https://clist.by/account/lucifer1006/resource/leetcode.com/
- https://clist.by/account/winter_training/resource/leetcode.com/

**Comment by nevikw39** [comment]
Me, too.
More specifically, my rating hasn't been updated since Biweekly Contest 75, in which is the last contest I partook.

**Comment by nevikw39** [comment]
The ratings have been updated.

**Comment by sdogsq** [comment]
Solved.  😆 
Thanks a lot. 🎆

**Comment by aropan** [comment]
I have a slow speed with updating a lot of leetcode users. I will update connected and top accounts only from now after every contest. Other accounts will updated rare.
