### ISSUE TITLE
Feature Request - Problems upsolved later are not detected by CLIST

### ISSUE THREAD

**Issue by l3456** [aropan/clist#185]
Write now, my understanding for problems status - Solved during contest, Upsolved later works only for Codeforces. Not for other sites.

It will be great to add some mechanism to tell CLIST that the problem has been solved.
Maybe ask for a submission link to verify that the problem was really solved. 

This will really helpful to track upsolving right from CLIST.

**Comment by nskybytskyi** [comment]
> works only for Codeforces. Not for other sites.
Technically, upsolving also sometimes gets detected for AtCoder [example](https://clist.by/account/nskybytskyi/resource/atcoder.jp/), but not all the time. 

That said, I would also like to see more resources detect upsolving. Besides, I'd love to see upsolving get displayed in the /problems section.

**Comment by aropan** [comment]
@l3456 you can check some mechanism here https://github.com/aropan/clist/issues/204#issuecomment-1492987995.

Honest upsolving works for [some resources](https://clist.by/resources/?upsolve=on).

@nskybytskyi upsolving added.
