### ISSUE TITLE
Color coding rating on platforms without official color scheme [Enhancement, Minor]

### ISSUE THREAD

**Issue by nskybytskyi** [aropan/clist#186]
Clist uses color coding for contest ratings on all platforms with a concept of contest rating. However, not all platforms have an official color coding scheme. Most notable examples include LeetCode, HackerEarth, and PrepBytes. I wonder how you decide which color scheme to use in such cases? 

For some platforms like LeetCode the current schemes are standard and make perfect sense. However, for other platforms the cutoff numbers appear to be random. For example, HackerEarth cutoffs are 1250-1450-1600-1700-2000. However, their website only mentions cutoffs like [1600](https://www.hackerearth.com/challenges/competitive/april-easy-22/) and [1800](https://www.hackerearth.com/docs/wiki/developers/hackerearth-ratings/). 1600 is the cutoff to win prizes in their easy monthly competition (subjectively Div. 3 difficulty), and 1800 is the cutoff between Div. 1 and Div. 2.

On Codeforces, Div. 3 ends with cyan, and Div. 1 starts with yellow, but in the current color scheme Div. 3 ends with blue, and 1800 is mid red. I would therefore prefer the following color scheme:

- 0000-1200 gray
- 1200-1400 green 🟢
- 1400-1600 cyan
- 1600-1800 blue 🔵 
- 1800-2000 orange 🟠 
- 2000-2200 red 🔴 
- 2200-9999 target 🎯 

It also should be noted that they changed the rating system somewhere around last June (it hasn't been publicly announced). It is (subjectively) much easier to gain rating ever since. For example, the number of targets more than doubled during this period. Hence I also propose raising the cutoff for being a target from 2000 to at least 2100, preferably 2200.

Ideally, we should ask HackerEarth administration if they plan to introduce official color coding for contest ratings, but I'm afraid we'll have to wait a long time for their response.

**Comment by aropan** [comment]
Sounds good. I set the color scheme for HackerEarth.

I usually use my inner intuition when choosing rating colors. 🙂

**Comment by nskybytskyi** [comment]
Thank you! I sent an email to their admins proposing the same color scheme, waiting for a response. Speaking of HackerEarth, it appears that the top ratings shown on https://clist.by/resource/hackerearth.com/ are way off from the actual values https://www.hackerearth.com/leaderboard/contests/rated. Perhaps ratings aren't updated properly for accounts that are not registered on clist?

**Comment by aropan** [comment]
How quickly is the rating updated after a contest?

**Comment by nskybytskyi** [comment]
Unfortunately, I cannot give you a single number that will be correct in all situations. It appears that 5 days is a very optimistic estimate. For example, they had a contest on the 9-th of April and the ratings are still pending. 

Do you check for rating updates on user profile pages or are they somehow accessible grouped by contest? In the latter case, I have a workaround in mind.

**Comment by aropan** [comment]
Rating updates from profile pages.

**Comment by nskybytskyi** [comment]
My idea was to trigger pulling for rating updates in a contest whenever we see a new individual rating change in that contest. If I understand correctly, this happens when I remove and add my account back (this is how I kept my rating updated so far). 

So basically any interested user can trigger a rating update for the entire contest. Fortunately, this cannot be abused, as the contest-wise update will be triggered only if we see a _new_ change, meaning that one contest can be pulled at most once (there are no rollbacks on HackerEarth as far as I'm aware).

**Comment by aropan** [comment]
_...when I remove and add my account back..._

Nice move. 🙂

**Comment by aropan** [comment]
@nskybytskyi I did trigger to update contest ratings on updating account rating five months ago. Have you noticed any changes? )

P.S. Of course, I should have done this message earlier.

**Comment by nskybytskyi** [comment]
> @nskybytskyi I did trigger to update contest ratings on updating account rating five months ago. Have you noticed any changes? )

I haven't been competing since June so can't tell if anything changed. Will try sometime soon and let you know.

**Comment by nskybytskyi** [comment]
@aropan well I just participated in CodeChef and it is already updating. Not sure if it is a scheduled update or triggered by a user, but fast either way
