### ISSUE TITLE
AdventofCode account not showing up in resources

### ISSUE THREAD

**Issue by Prakash771** [aropan/clist#187]
My account is not showing up on clist. It has a blank space between first and last name. Is there a requirement for how the name should be? Should it be linked to github to get detected on clist?

![image](https://user-images.githubusercontent.com/25455657/166218876-8f97fc51-54a5-448c-ab44-60fd508f493c.png)

**Comment by aropan** [comment]
@Prakash771 Do you have the official score? Clist detects accounts from standings for each day only. As an example from here https://adventofcode.com/2021/leaderboard/day/15.

**Comment by Prakash771** [comment]
No, I'm not in the official standings. I'm closing the issue, thanks.
