### ISSUE TITLE
'Tag' column in problems table doesn't display entirely

### ISSUE THREAD

**Issue by breakTBB** [aropan/clist#188]
![image](https://user-images.githubusercontent.com/16484507/169657658-c1b33223-d090-444f-a900-ccd2fbd51d9a.png)
as you can see.
Chrome 101.0.4951.64 (x64)

**Comment by aropan** [comment]
Does horizontal scroll work? 
https://user-images.githubusercontent.com/1968460/169661785-a85fe4da-adb3-4cb7-a926-1d1c22788b03.mov

**Comment by breakTBB** [comment]
it seems you fixed it, thanks!
