### ISSUE TITLE
Correct link to contest in calender

### ISSUE THREAD

**Issue by nevikw39** [aropan/clist#190]
Hello,

It's really convenient to create a calendar on CLIST and get notifications about various OJ.

But the description of events seems to be the home page of OJ. In the index of CLIST, there are the links to each specific contest.

So could you update the link in the events?

Thanks!

**Comment by aropan** [comment]
Do you say about this https://clist.by/settings/calendars/?

**Comment by aropan** [comment]
There are urls to contests in ics calendar:
![image](https://user-images.githubusercontent.com/1968460/169708885-92f09ceb-afd2-44fe-bce8-08fa23289b8b.png)

**Comment by aropan** [comment]
Oh, I understand. I try subscription via google calendar and see:
![image](https://user-images.githubusercontent.com/1968460/169709107-af9496a2-2563-4a7e-95a6-3a468e04e88d.png)

Mac OS calendar looks like:
![image](https://user-images.githubusercontent.com/1968460/169709165-8fb61086-9d87-44be-be76-871878a5cdc0.png)

**Comment by aropan** [comment]
I fixed it a bit:
<img src="https://user-images.githubusercontent.com/1968460/169719356-0188ea7a-d2e7-4396-9b03-7122832dc6a2.png" width="500">


You can wait for the calendar google cache to be dropped or create a new calendar to test.

And add option to configure events description:
<img src="https://user-images.githubusercontent.com/1968460/169719464-61502fb7-4219-4ce3-a627-3d3e2e43f415.png" width="500">

**Comment by nevikw39** [comment]
Oh! It's cool!

By the way, could we custom the description like: `Link: {{Url}}`?

**Comment by nevikw39** [comment]
Hello @aropan,

I mean that currently the **``location''** of a contest event is a link to the corresponding OJ. Can it link to the contest itself properly, too?

In fact I'm writing a bot working on the calendar. I'd like to have it to get the contest link.

Thanks!

![image](https://user-images.githubusercontent.com/20489759/170328628-294af18b-1c2c-4092-b018-2a4b073f56af.png)

![image](https://user-images.githubusercontent.com/20489759/170328740-b181c81a-80f8-4454-86a0-e08008c479d0.png)
