### ISSUE TITLE
Hackerrank, Hackerearth Accounts are not fectched!

### ISSUE THREAD

**Issue by vasanthgk02** [aropan/clist#195]
Hey, I have account in both hacerrankt and hackerearth. My username is vasanthgk02. When I enter it in accounts search bar hackerearth and hackerrank accounts are alone not showing! Please do check. To mention your platform is really awezome and I am new to your platform!

Link to my both profiles

[https://www.hackerrank.com/vasanthgk02](url)
[https://www.hackerrank.com/vasanthgk02](url)

![image](https://user-images.githubusercontent.com/74846250/176339485-7407fb0e-f561-4739-936e-a56c7f3bd01b.png)

**Comment by aropan** [comment]
You can search accounts after participating in a contest and after parsing statistics.
