### ISSUE TITLE
Unlist "Arjun's test page" from CodeChef ongoing contest

### ISSUE THREAD

**Issue by chanukyapatnaik** [aropan/clist#2]
It is a test page public a while back while testing internally at CodeChef and it seems clist bot crawled at that point and put it on the list of ongoing contests. Could you please remove it? Thanks

link to the page: https://www.codechef.com/ARJUTEST?utm_source=contest_listing&utm_medium=link&utm_campaign=ARJUTEST

**Comment by aropan** [comment]
Done
