### ISSUE TITLE
Add CodeSignal? 

### ISSUE THREAD

**Issue by ofou** [aropan/clist#200]
First of all, just came across `clist` and I think it's an amazing resource! I was looking into the Resources and I didn't find [CodeSignal](https://app.codesignal.com/leaderboard/). I think this will be a great addition to the list, and there's an active community over there too.

**Comment by sposting** [comment]
No. Codesignal can take their [proctored](https://support.codesignal.com/hc/en-us/articles/360039872174-What-is-proctoring-and-how-does-it-work-) tests and shove them right up their аsses. No one should encourage, or even acknowledge such disgusting, offensive, invasive, and improper practices. 

This is without even getting into the security risks with having your personal data, including GOVERNMENT ID, microphone feed, webcam footage, and screen feed, all being recorded and stored for some dumbаss in Mumbai or wherever to look at while jеrking off (to make sure you're not cheating, of course...),

There is zero overlap between people who solve competitive programming questions and people who willingly subject themselves to having their privacy completely rаped, all to try solving 4 easy questions for the luxury of maybe working at a company full of other losers who are just as pathetic as they are.
