### ISSUE TITLE
clist does only display the new ID/domain-name records

### ISSUE THREAD

**Issue by Deep-Coder-zhui** [aropan/clist#201]
when I changed leetcode-us ID or leetcode-cn domain name, clist didn't display the merged records but the new ID/domain-name records. for example, [GuardianEmptyCoder](https://clist.by/account/guardianemptycoder/resource/leetcode.com/)

**Comment by aropan** [comment]
What is your previous id?
How can I understand which litcode ID has changed and which one is new?

**Comment by aropan** [comment]
@Deep-Coder-zhui If there is any information, then reopen it.
