### ISSUE TITLE
Feature Request - Allow users to mark problems, contests etc as fav

### ISSUE THREAD

**Issue by l3456** [aropan/clist#204]
Clist is the best to track our progress across multiple sites, but I guess it's mostly read only.

I would love to see a feature where users can interact with problems, contests etc.
like allowing users to mark a problem as favourite, todo, solved and maybe add some info around it like adding a note or personal tags. 

At the very least, allowing users to mark a problem as already solved would be very useful as currently clist doesn't detect solves correctly across all sites.

**Comment by aropan** [comment]
Try https://github.com/aropan/clist/discussions/226 and https://github.com/aropan/clist/discussions/227 and leave feedback about it.

**Comment by aropan** [comment]
Problem note was added #267.
