### ISSUE TITLE
Can I add more websites to resources?

### ISSUE THREAD

**Issue by chinesedfan** [aropan/clist#205]
Like contributing a plugin or somehow? Thanks.

**Comment by ajeetgupta80** [comment]
yes u can add hackwithinfy

**Comment by ajeetgupta80** [comment]
yes u can add hackwithinfy

**Comment by YashNandwana** [comment]
> yes u can add hackwithinfy

how do I do it?...can you help

**Comment by aropan** [comment]
You can share a link to a resource (better if it has schedule events), API if available. After this I add resource myself.
