### ISSUE TITLE
GFG Google  calendar : Interview series contest is not showing.

### ISSUE THREAD

**Issue by anuragdw710** [aropan/clist#206]
<img width="960" alt="2022-09-24" src="https://user-images.githubusercontent.com/78266752/192051396-16147c78-f19a-4489-9c62-dcabbcbe47eb.png">

**Comment by anuragdw710** [comment]
On 25 sunday there is a contest but not showing.

**Comment by aropan** [comment]
Thanks for the report. Fixed.
