### ISSUE TITLE
[Bug] Contests from tlx.toki.id no longer listed from the API

### ISSUE THREAD

**Issue by prabowo02** [aropan/clist#218]
The list of contests queried from https://clist.by:443/api/v2/contest/?start__gte=2023-01-01 does not show the contest from [TLX](https://tlx.toki.id), but in fact, they have one on 7th January ([TROC #30](https://tlx.toki.id/contests/troc-30)).

Up until TROC 28, the contest can still be seen from the API. My suspicion is that recently the contest name is rebranded from _**TOKI** Regular Open Contest_ to _**TLX** Regular Open Contest_ starting from TROC 29.

Could you help in investigating this matter?
Thank you in advance

**Comment by aropan** [comment]
You see the first 100 contests only for queries. `"estimated_count": 1` is wrong sometimes (or often).

You could use `limit=1000` to get more contests for one query or use `offset=100` and `offset=200` to get next contests as pagination.

Also, you could use `total_count=true` to get honest count of contests (313 for your query). But this request is heavier than without it and less preferred.

**Comment by prabowo02** [comment]
You're right, I can now see the contest correctly after increasing the limit.

Sorry for the false alarm, and thank you for your help checking this matter. I will close this issue.
