### ISSUE TITLE
Filter out long contest in google calendar for a particular website 

### ISSUE THREAD

**Issue by prabh1601** [aropan/clist#230]
When I go to [Atcoder's google calendar (from resources)](https://calendar.google.com/calendar/u/0/embed?src=vdobhfoodrv59522b684lhfs7c@group.calendar.google.com), I also see Atcoder Heuristic contests - which are by default long contests. 

However, I don't desire to see them while importing the same calendar to my google calendar. Is there a work around for this ?

**Comment by aropan** [comment]
You could configure [filters](https://clist.by/settings/filters/) and generate a new [calendar](https://clist.by/settings/filters/) special for you.

**Comment by prabh1601** [comment]
Oh, that's great! Thank you  :smile:
