### ISSUE TITLE
Outdated LeetCode Rankings

### ISSUE THREAD

**Issue by samyak1409** [aropan/clist#231]
[LeetCode](https://leetcode.com) keeps updating their rankings till nearly a week after the end of a contest, so please set to fetch the rankings after a week or so, so that rankings are not outdated.

See the outdated rankings:

![Screenshot ()](https://user-images.githubusercontent.com/42683801/225944859-5570b5b5-e054-48d2-b848-2549cfdea0c6.png)
![Screenshot ()](https://user-images.githubusercontent.com/42683801/225944892-3702cce6-dba5-4fb9-b899-cd2a92195fee.png)

**Comment by aropan** [comment]
Too many accounts to update. And I asked for https://leetcode.com/discuss/feedback/1732120/rating-change to make it easier to upgrade, but I don't think anyone cares.

But you can add this account to your profile for periodic update.
https://clist.by/account/samyak1409/resource/leetcode.com/
<img width="530" alt="image" src="https://user-images.githubusercontent.com/1968460/229290955-ceb619b7-c5bf-4a9f-9379-534e85709655.png">
