### ISSUE TITLE
Total number of participants in Leetcode weekly contest 377 is showing wrong.

### ISSUE THREAD

**Issue by RajKumarRay** [aropan/clist#232]
In first question Itself , the total number of accepted users is >12k. then How the number of participants will be 5k only.
Please have a look at this.

**Comment by aropan** [comment]
Are you mean [Weekly Contest 337](https://leetcode.com/contest/weekly-contest-337/ranking)? May be some updating was in leetcode because I see >16k https://leetcode.com/contest/weekly-contest-337/ranking/659/.
