### ISSUE TITLE
"Starters 77 Testing Page" shown as a live contest with 100 days duration

### ISSUE THREAD

**Issue by brobat6** [aropan/clist#233]
It should be removed from contest list altogether, it is a private page for testing purposes only.

**Comment by aropan** [comment]
I don't see it. If some future events are no longer available, they will be automatically deleted after 2 hours.

**Comment by brobat6** [comment]
![image](https://user-images.githubusercontent.com/37776105/229665020-0838792f-93d1-4dae-8e13-e7e7d27f5fcc.png)

Same result whether I log in from my account or open the website from an incognito window.
