### ISSUE TITLE
query /api/v2/coder, the username paramter can only be myself, otherwise 401 error

### ISSUE THREAD

**Issue by hiaatcnd** [aropan/clist#234]
It is successful on the web page, but the request fail

![image](https://user-images.githubusercontent.com/17536825/228039997-e9c41529-9676-490f-9c47-84e8d193baea.png)
![image](https://user-images.githubusercontent.com/17536825/228040132-c6ea2d4b-8a73-4520-b8f4-ad132ae4d0ad.png)

**Comment by aropan** [comment]
Thanks for your reaction. There is a problem with `username` using twice - for API `username` and coder filter `username`. So you could use query header to pass API key (`Authorization: ApiKey username:api_key`).

And I don't want to break the v2 API and so made a new v3 API with fix field name for filtering. Check here https://clist.by/api/v3/doc/.
