### ISSUE TITLE
Add Tags Page

### ISSUE THREAD

**Issue by ofou** [aropan/clist#235]
It'd be very useful to have a Tags page like this:
<img width="893" alt="Screenshot 2023-04-08 at 04 56 49" src="https://user-images.githubusercontent.com/12256669/230712978-d9d66533-30d6-4588-90be-f6560ea4812b.png">

To show the most used tags on all problems.

**Comment by aropan** [comment]
Check [this](https://clist.by/problems/?search=&groupby=tag&status=&chart=&sort_order=desc&sort=):


https://github.com/aropan/clist/assets/1968460/790c1678-efc6-4948-964a-803935dede88
