### ISSUE TITLE
Enable sorting for problems page

### ISSUE THREAD

**Issue by ofou** [aropan/clist#236]
This is highly needed, especially for rating on problems.

**Comment by aropan** [comment]
Added rating sort:
<img width="183" alt="image" src="https://github.com/aropan/clist/assets/1968460/00e97754-ac07-4d63-ad43-0b6bc3d5358e">
<img width="118" alt="image" src="https://github.com/aropan/clist/assets/1968460/9ed2c9e4-e3bb-4fa8-9d97-cb19cc9e3365">
