### ISSUE TITLE
Добавить платформу CPython.uz

### ISSUE THREAD

**Issue by archon1999** [aropan/clist#237]
Прощу добавить платформу CPython.uz в clist.by

Я являюсь основателем.  Эта соревновательная платформа. Часто проходят турниры разного формата.

Есть [API,](https://cpython.uz/api/contests) вся необходимая информация предоставлена.

P.S. Вроде aropan русскоговорящий. Не стал использовать переводчик.

**Comment by aropan** [comment]
Через браузер пока работает, но с сервера проблема с сертификатом:

```
> curl 'https://cpython.uz/'
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

> wget 'https://cpython.uz/'
--2023-05-07 11:27:48--  https://cpython.uz/
Resolving cpython.uz (cpython.uz)... 193.164.17.14
Connecting to cpython.uz (cpython.uz)|193.164.17.14|:443... connected.
ERROR: cannot verify cpython.uz's certificate, issued by ‘CN=ZeroSSL RSA Domain Secure Site CA,O=ZeroSSL,C=AT’:
  Unable to locally verify the issuer's authority.
To connect to cpython.uz insecurely, use `--no-check-certificate'.
```

@archon1999 посмотрите все ли хорошо у вас с сертификатом? Можно начать отсюда https://whatsmychaincert.com/?cpython.uz:

```
Test Your Server
cpython.uz is misconfigured
```

**Comment by archon1999** [comment]
Исправил, теперь должно работать.

**Comment by aropan** [comment]
@archon1999 а какие границы для званий в рейтинге https://cpython.uz/competitions/contests/rating ?

**Comment by archon1999** [comment]
1200
1400
1600
1800
2000
2200
2400
2500
2600

**Comment by aropan** [comment]
@archon1999 а есть названия званий для каждого?

**Comment by archon1999** [comment]
NEOFIT = 0
RITOR = 1200
LIKTOR = 1400
LEGAT = 1600
MASTER = 1800
MAGISTR = 2000
PRETOR = 2200
ARCHON = 2400
POLEMARCH = 2500
MALIK = 2600
MAYAR = 2800
VALAR = 3000

**Comment by aropan** [comment]
@archon1999 добавил https://clist.by/resource/cpython.uz/
