### ISSUE TITLE
filters using the api

### ISSUE THREAD

**Issue by gilcu3** [aropan/clist#239]
I cannot use filters using the api v3, what are the correct parameters?
`https://clist.by/api/v3/contest/?upcoming=true&filtered=true&format=json`

**Comment by aropan** [comment]
@gilcu3 I see that you have one filter for `list`. Could you add this filter for `api` also and it should work.

**Comment by gilcu3** [comment]
I just did, still getting the same result.

**Comment by aropan** [comment]
Oh, it was a bug. It used to work with `category=api` param only. Fixed.
@gilcu3 please check it.

**Comment by gilcu3** [comment]
working now, thanks!
