### ISSUE TITLE
can i merge 2 accounts Codeforces ?

### ISSUE THREAD

**Issue by kodomotachi** [aropan/clist#241]

**Comment by aropan** [comment]
@kodomotachi Are these account merged (same) on coderforces?

**Comment by kodomotachi** [comment]
no, but I think some people will have the need to see the performance of multiple Codeforces's accounts at the same time

**Comment by aropan** [comment]
Why? What about the rule of codeforces https://codeforces.com/help?locale=en#q6?:
_Don't create more than one account, if you have forgotten the password, use the password reminding system._

**Comment by aropan** [comment]
Or mixed profile https://clist.by/profile/cf:aropan,cf:tourist/.
