### ISSUE TITLE
USACO: Parsing Multiple Divisions

### ISSUE THREAD

**Issue by Aviously** [aropan/clist#242]
During a USACO contest, anyone who received a perfect score is able to participate in the next division during the same contest. The [usaco.org](http://usaco.org/index.php) contest page writes:

> All participants start in the bronze division, and those who score particularly well in a contest will be promoted to the next division. Contestants scoring particularly highly will be automatically promoted to the next division...

However, it looks like on clist.by, only the first contest gets parsed. For example, [the profile](https://clist.by/coder/Aviously/?search=resource:usaco.org) only shows one entry for Dec. 15, 2015, even though there were scores in multiple divisions (e.g. [here](http://usaco.org/current/data/dec15_silver_results.html) and [here](http://usaco.org/current/data/dec15_gold_results.html)).

Thanks for this great contest resource.

**Comment by aropan** [comment]
Thanks for the report. I hope I fixed it.
