### ISSUE TITLE
Leetcode upsolving blue color issue

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#245]
@aropan  Thanks for a great website you have provided for all of us.

==
On upsolving I have some quesions/suggestions

Even though I solved all Q1s. Some Q1s are not shown as upsolved.
Some non Q1s are shown as upsolved. Some are not shown.
Unable to understand how this works, or when this color changes to blue.

It will really nice if the color changes to blue 
- automatically as soon as the problem is solved ( in contest / problem editor )
- or, when the 'Update' button is clicked
![image](https://github.com/aropan/clist/assets/8236389/7300d843-7f67-43cc-92dd-a999372bfcea)

Screenshot:
![image](https://github.com/aropan/clist/assets/8236389/6db923db-74a3-46ae-82a1-e23d706fe7fd)

Link
https://clist.by/account/pgmreddy/resource/leetcode.com/

==

As of today leetcode is shown to have upsolving

https://clist.by/resources/?upsolve=on

![image](https://github.com/aropan/clist/assets/8236389/59882564-dab5-4532-92ee-b52362d1dbc0)

**Comment by aropan** [comment]
I can't get all solved problems. And get only recent successful solutions from a user profile:
<img width="878" alt="image" src="https://github.com/aropan/clist/assets/1968460/36ac753e-6508-48f3-8474-3e674f52aa6b">

If you solve actively then your profile will be updated every day automatically. But if you have big number solutions of for different problems then clist have a gap in some solved problems. You can resolve it with manual updating via profile if you have plan to solve a lot of problems.  

I added tooltip about it here https://clist.by/resources/?upsolve=on:
<img width="1223" alt="image" src="https://github.com/aropan/clist/assets/1968460/cc9732cc-685d-4624-ab2f-2e7f5b701df1">
