### ISSUE TITLE
Icon is not spinning on account/resource page, when spinning on coder page

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#246]
@aropan Thanks for a great website you have provided for all of us.

==

I am trying the solution given at https://github.com/aropan/clist/issues/245#issuecomment-1575494459

page 1 - https://clist.by/account/pgmreddy/resource/leetcode.com/
page 2 - https://clist.by/coder/pgmreddy/

When we click on Update button on page 1 above
then
the icon is spinning on page 2
but not spinning on page 1

please show
spinning icon ( or show "in progress" text on hover )
in both places
while Update is running

Otherwise, most people click update again and again, with no result seen below

![image](https://github.com/aropan/clist/assets/8236389/ac75d23b-a54b-4155-80c2-45749d0e4363)

**Comment by aropan** [comment]
Every duplicate click on update get message about it:
<img width="748" alt="image" src="https://github.com/aropan/clist/assets/1968460/5b2b18ef-c527-4d59-a0d9-f0c87cabf0a0">

**Comment by manoharreddyporeddy** [comment]
true
but the message "already updated" is misleading

because the spinner in the page 2 - https://clist.by/coder/pgmreddy/
continues to update for next 15 mins - at which point we can really say "updated"

so
the message "already updated"
can be changed to "in progress" - which will suffice for now i think 
i can also be changed to "in progress, might take upto 15 minutes" is even better


===

thanks for your hard work & time

**Comment by manoharreddyporeddy** [comment]
"already updated" message
may be changed to
"already in progress, may take upto 15 minutes to complete"

**Comment by aropan** [comment]
Replaced the message with "Update in progress". Added visual spin effect and block repeat click while the update in progress.

**Comment by manoharreddyporeddy** [comment]
Spinner works perfectly
thank you
