### ISSUE TITLE
Missing green icon in /account/.../resource/

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#250]
Thank you for your efforts.

---

At https://clist.by/coder/pgmreddy/
I can see green icon
![image](https://github.com/aropan/clist/assets/8236389/afaff24f-8866-4e86-8d8e-7feb9494f137)

However
At https://clist.by/account/pgmreddy/resource/leetcode.com/
green icon is missing
![image](https://github.com/aropan/clist/assets/8236389/3df8d750-b4a0-4d66-866e-049654d753fa)

Note:
This happens when viewing from
another account

**Comment by manoharreddyporeddy** [comment]
@aropan

**Comment by manoharreddyporeddy** [comment]
Note:
This happens when viewing from
another account

**Comment by aropan** [comment]
I fixed it. Let me know if not yet.

**Comment by manoharreddyporeddy** [comment]
Working perfectly now. Thank you.

![image](https://github.com/aropan/clist/assets/8236389/9ce55e3b-178f-41a1-9bdd-36387ddd3610)
