### ISSUE TITLE
Adding solved.ac to resources

### ISSUE THREAD

**Issue by shiftpsh** [aropan/clist#251]
Can I request my site [solved.ac](https://solved.ac/) — which is an extension to the [Baekjoon Online Judge](https://www.acmicpc.net/) in South Korea — to be added to the resource?

- Most of the [problems](https://solved.ac/en/problems/all) have a user-contributed difficulty level.
  - The colors of the levels are brown(bronze; 1-5), gray(silver; 6-10), yellow(gold; 11-15), green(platinum; 16-20), blue(diamond; 21-25), and red(ruby; 26-30).
- [Users](https://solved.ac/en/ranking/tier) get "rated" by all-time problem solved, based on the aforementioned difficulty.
- [Contests](https://solved.ac/en/arena) will be held soon with a separate rating system — users will have both a contest rating and a problem rating after August.

For updating data, please check out the following API endpoints:

- Users (50 per page): https://solved.ac/api/v3/ranking/tier?page=1
- Problems (50 per page): https://solved.ac/api/v3/search/problem?query=&page=1

The endpoints are rate-limited to 128 requests per 15-minute window.

**Comment by aropan** [comment]
Added contests part (contests, users from them and contest ratings) https://clist.by/resource/solved.ac/.
