### ISSUE TITLE
Update takes a long time to complete.

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#253]
Thanks for the website you have provided & hard work you put in. @aropan

===

The update process takes a long time to complete.
If anything can be done, like run in background in a queue will he helpful. However 2 updates should not overlap.

![image](https://github.com/aropan/clist/assets/8236389/60367d25-7fcc-4b31-ac09-5053c5b8d4d1)

**Comment by aropan** [comment]
What is resource?

**Comment by manoharreddyporeddy** [comment]
resource is LeetCode
like when i am here https://clist.by/account/pgmreddy/resource/leetcode.com/

**Comment by aropan** [comment]
Duplicate #373
