### ISSUE TITLE
Question names changed

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#254]
Thanks for the website you have provided & hard work you put in. @aropan 

====

looks like, the question name is changed for a few

it will be great if you could fix them

https://leetcode.com/contest/biweekly-contest-27/problems/make-two-arrays-equal-by-reversing-sub-arrays/
	close match is
https://leetcode.com/contest/biweekly-contest-27/problems/make-two-arrays-equal-by-reversing-subarrays/

https://leetcode.com/contest/biweekly-contest-66/problems/minimum-number-of-buckets-required-to-collect-rainwater-from-houses/
	close match is
https://leetcode.com/contest/biweekly-contest-66/problems/minimum-number-of-food-buckets-to-feed-the-hamsters/

**Comment by manoharreddyporeddy** [comment]
@aropan 
possibly i can fix these
if so, please point to a file, i will raise a pull request

**Comment by aropan** [comment]
Oh, Q1 (3) link doesn't work here https://leetcode.com/contest/biweekly-contest-27/ranking.

**Comment by aropan** [comment]
I temporarily fixed it.

**Comment by manoharreddyporeddy** [comment]
For Q1 (3) link
raised a bug for leetcode.com here - https://github.com/LeetCode-Feedback/LeetCode-Feedback/issues/15163
