### ISSUE TITLE
Update another account, that has no coder login

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#255]
Thanks for the website you have provided & hard work you put in. @aropan 

====

Issue:

Assuming an account with name ABCABCABCABC exists

For example:
https://clist.by/account/ABCABCABCABC/resource/leetcode.com/
However they don't have coder login

How to update latest contests
for above account
without coder login ?

====

Use case:

This is required when
For example, they don't have a coder account ( example https://clist.by/coder/ABCABCABCABC/) and so it does not update automatically
But I want to compare my latest contests rating to them using Vs
https://clist.by/versus/pgmreddy/vs/lc:ABCABCABCABC/
the comparison is not successful since latest contests are not available in ABCABCABCABC

====

Work around:

The work around i do as of today is 
add their username to alternate coder account and remove it ( so they can create their coder account )
and after a few minutes it gets updated

However this is tedious process
when i want to compare to 10 people who do don't know have coder account

Also this is only reason I have alternate account. Once there is a way to update others account ( without coder login ), there is really no good reason for me to use my alternate coder account.

====

Appreciate your help on how to update others account, without coder login. Thanks again for your time.

**Comment by manoharreddyporeddy** [comment]
May be

Some solutions can be

Comparison like this - https://clist.by/versus/pgmreddy/vs/lc:ABCABCABCABC/
- should trigger Update for all compared, automatically
- Or, there should be update button under each name, so people can update manually


@aropan

**Comment by aropan** [comment]
Do you want to update statistics or ratings for a specific account? Updating statistics applies to all accounts, but rating updates only apply to selected ones (top or linked accounts). This is because rating updates for all accounts require extended time. You can find more information here: https://leetcode.com/discuss/feedback/1732120/rating-change.

**Comment by manoharreddyporeddy** [comment]
thanks for reply @aropan 

I was asking a more simple one - for already completed contests

For example
I pick at random a user
like https://leetcode.com/balakrishnan_v/

they don't have code login
https://clist.by/coder/balakrishnan_v/

![image](https://github.com/aropan/clist/assets/8236389/33a55409-f62d-4461-80ff-2a3dc8ae4e3c)


so their account is not updated ( some gaps at different places for different users )

https://clist.by/profile/lc:balakrishnan_v/
![image](https://github.com/aropan/clist/assets/8236389/7490895a-3181-4691-b861-fd4361296d4e)


Now if i want to compare with them like
https://clist.by/versus/lc:balakrishnan_v/vs/pgmreddy/

the comparison is not done properly because   the data for some contests is missing

so it is possible to trigger an automatically update with comparison is done ?
or,  provide an option to update with update button ?  like below - under each user?

![image](https://github.com/aropan/clist/assets/8236389/82bedebd-3ce9-4322-ad7e-b825cc209902)

**Comment by manoharreddyporeddy** [comment]
thanks for the hard work you put in @aropan 

===

A request for this ticket, since a month passed by

every week, after leetcode contest
I use the comparison /vs/ url to compare ratings
however since some don't have clist account, so they (/vs/lc:ABC) are not non-updating
so comparison with these users is not so useful

ideally, comparison /lc:a/vs/lc:b should trigger an update for both a & b accounts being compared so that after few mins we can get latest data, & comparison is correct

As others I compare some who are just above me, so updates are important to compare correctly

if possible
I could help on this, i can code in JavaScript well, we can use chat GPT to convert to your language of preference to merge above feature.

Alternatively, if you have an alternate way to trigger update for a non existing account  lc:ABC, please let me know that will help greatly everyone else too

**Comment by manoharreddyporeddy** [comment]
thanks for the hard work you put in @aropan 

===

is it possible to go to a profile like below, and trigger update, using a temp/dummy account ?
https://clist.by/profile/lc:balakrishnan_v/

**Comment by aropan** [comment]
> is it possible to go to a profile like below, and trigger update, using a temp/dummy account ?
> https://clist.by/profile/lc:balakrishnan_v/

No, if resource have verification you need verify account before trigger update.

> ideally, comparison /lc:a/vs/lc:b should trigger an update for both a & b accounts being compared so that after few mins we can get latest data, & comparison is correct

You don't need addition updating accounts, because resource standings (contests, ranks, scores) update for all accounts.

**Comment by aropan** [comment]
Or perhaps you want to compare ratings graphs? Then it is problem. But I don’t plan to add updates to other people’s accounts yet.

You could invite them to register on CLIST and add accounts - then these account will be update automatically.

**Comment by manoharreddyporeddy** [comment]
I did invite some 10+ till now 😊

But if they don't register
still love to see their accounts updated temporarily
like the ones in Top10 are updated (some dont have accounts)

only interested if I am comparing via   `Versus` page  or  `Lists` pages only.

===

![image](https://github.com/user-attachments/assets/b522d83a-5c6f-4987-b7d6-bf2c8acdff34)
