### ISSUE TITLE
Update another account, that has coder login, via another coder login

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#256]
@aropan thanks for your hard work, & for the website you have provided

=====

Use case:
I am logged in

Some others have account, but it is not updating daily
Example - https://clist.by/account/ABCABCABCABCABCABC/resource/leetcode.com/

If you an enable Update button on their account, when I have already coder logged in, it will help

That way, Vs url will be useful to compare latest data
https://clist.by/versus/pgmreddy/vs/ABCABCABCABCABCABC/

**Comment by aropan** [comment]
Who is ABCABCABCABCABCABC?

**Comment by manoharreddyporeddy** [comment]
It was    venkateshwar1996
https://clist.by/account/venkateshwar1996/resource/leetcode.com/

I asked them to click on Update button, they did ast week or so


@aropan

**Comment by aropan** [comment]
Same as #255 - not needed updating accounts for versus.
