### ISSUE TITLE
Rating predictions

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#257]
@aropan thanks for great website you maintain

====

I use below for ratings predictions:

https://lccn.lbao.site/predicted/weekly-contest-356
https://lccn.lbao.site/

====

Above is great to have on clist.by

For example

if contest is not yet rated
going to the contest page should provide the predicted ratings or all users
these ratings are released after 3 to 5 days by leetcode

For past contest - it shows "Rating Change"   https://clist.by/standings/weekly-contest-355-44938475/
For just completed contests - it shows "Predicted Rating Change"   https://clist.by/standings/weekly-contest-356-45092360/

Same can be shown at resource level
https://clist.by/account/pgmreddy/resource/leetcode.com/
under Rating  in italics red color to indicate it is predicted ( or like )

**Comment by aropan** [comment]
Added.

https://clist.by/standings/weekly-contest-369-47240093/

<img width="1233" alt="image" src="https://github.com/aropan/clist/assets/1968460/43ff3139-2b46-4603-8a7b-0496eacf8e80">

**Comment by manoharreddyporeddy** [comment]
Excellent @aropan 
Predicted Rating Perf is very useful too.
