### ISSUE TITLE
Coder account for leetcode.com resource

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#258]
Thanks for your time on seeing these issues @aropan 

====

Go to https://clist.by/standings/weekly-contest-355-44938475/

Click on Writer leetcode
![image](https://github.com/aropan/clist/assets/8236389/d09f77e0-a8b7-4c2a-a807-43d197d170f5)

It goes to https://clist.by/coder/bilolbek_aka/?search=resource:leetcode.com

Was expecting it to go to
- https://clist.by/coder/leetcode/ which is 'Not Found' for now
or
- https://clist.by/resource/leetcode.com/  which exists

**Comment by aropan** [comment]
Fixed.
