### ISSUE TITLE
Languages filter missing in newer contests

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#260]
@aropan thanks for the great site & hard work you put in

======

Languages filter missing in newer contests
How to enable for newer contests ?

===

Old contest - drop down does not exist
https://clist.by/standings/weekly-contest-76-12003097/

![image](https://github.com/aropan/clist/assets/8236389/edeaf82c-249b-40c7-87b4-2eb2ae52d773)

New contest - drop down does not exist
https://clist.by/standings/weekly-contest-340-42173027/

![image](https://github.com/aropan/clist/assets/8236389/b6ef10ef-cec5-47c8-b3b0-c8851e5d75c8)

**Comment by aropan** [comment]
I returned `languages` for newer contests. 
<img width="652" alt="image" src="https://github.com/aropan/clist/assets/1968460/1de449e2-6c73-480d-91a6-025b9074cfb5">
<img width="727" alt="image" src="https://github.com/aropan/clist/assets/1968460/805bb5be-3aed-4f80-a971-c98af1dfa84d">

**Comment by manoharreddyporeddy** [comment]
Thanks for your work @aropan 

===

I am unable to see languages for newer languages.
Maybe it got reverted ? Maybe I am missing something, please let me know.

https://clist.by/standings/weekly-contest-361-45767072/
https://clist.by/standings/biweekly-contest-112-45616879/

![image](https://github.com/aropan/clist/assets/8236389/7690896f-7cd7-4976-9298-071ea60ebce2)

![image](https://github.com/aropan/clist/assets/8236389/4b113a4f-3572-4fba-b660-4d669a6e39bf)

**Comment by aropan** [comment]
Thanks. Fixed.
