### ISSUE TITLE
Country ranking does not have Global ranking too

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#262]
@aropan Thanks the website, and for your time.

===

When we filter for a country

Example
https://clist.by/accounts/?search=&sort_column=rating&sort_order=desc&country=IN&resource=102

It shows country ranking
However Global Ranking will great to have

Example: https://leetcode-country-ranking.onrender.com/country/IN

![image](https://github.com/aropan/clist/assets/8236389/6e0ab9cc-1d6b-4784-91ba-ff092063af0c)

**Comment by aropan** [comment]
I added `Rank` to account page. And you can also use additional field `global_ranking` https://clist.by/accounts/?sort_column=rating&sort_order=desc&country=IN&resource=102&field=global_ranking.

**Comment by manoharreddyporeddy** [comment]
Thanks for adding! @aropan
