### ISSUE TITLE
Add leetcode_problem_rating ratings 

### ISSUE THREAD

**Issue by michelececcacci** [aropan/clist#263]
https://github.com/zerotrac/leetcode_problem_rating does an excellent job at calculating problem ratings, and i feel like clist could fetch them from here. I'd be willing to implement the feature myself

**Comment by aropan** [comment]
Isn't it the same as https://clist.by/problems/?resource=102&sort_order=desc&sort=rating (with a little bit differences)?

**Comment by michelececcacci** [comment]
Yeah, i don't know how i missed that. My bad. Closing the issue, and sorry for wasting your time
