### ISSUE TITLE
Filter for atcoder.jp?lang=ja

### ISSUE THREAD

**Issue by bqi343** [aropan/clist#264]
I don't speak Japanese :)

**Comment by aropan** [comment]
@bqi343 I also. )

**Comment by aropan** [comment]
Added. You can preview here #266.

**Comment by bqi343** [comment]
I'm confused, how do I keep atcoder.jp but filter out atcoder.jp?lang=ja? Do I specify something in host?

**Comment by aropan** [comment]
Try

https://github.com/aropan/clist/assets/1968460/e1d0e7e0-51e7-48e6-8de0-3f4e83eecd98
