### ISSUE TITLE
On clist.by, you don't include the Beginners Olympiad in Informatics Qualification Round 1 on September 23 from 6PM EDT - 9 PM EDT Link: https://lightoj.com/contest/bytemastersq1/ 

### ISSUE THREAD

**Issue by dylan1006498** [aropan/clist#269]
On clist.by, you don't include the Beginners Olympiad in Informatics Qualification Round 1 on September 23 from 6PM EDT - 9 PM EDT Link: [https://lightoj.com/contest/bytemastersq1/](https://lightoj.com/contest/bytemastersq1/)

**Comment by aropan** [comment]
Hm, please recheck. I see here https://clist.by/resource/lightoj.com/:
<img width="1185" alt="image" src="https://github.com/aropan/clist/assets/1968460/bb27c502-6dde-47fd-a551-6d81008bb9e2">
