### ISSUE TITLE
Rename "Rank" to "Overall rank"

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#272]
Thanks for your hard work @aropan 

===

In continuation to https://github.com/aropan/clist/issues/262

1 Since we are seeing a country rank on the left most column ( # )
"Rank" can be called as "Global Rank" ( "Global Ranking" is different column, can stay on right, when we add it )

![image](https://github.com/aropan/clist/assets/8236389/079f6ece-81bf-4774-8792-286043a95b37)

2 Just checking
when we add global_ranking, the current "Rank" is slightly different from "Global Ranking"
so not sure which is correct
felt both should be same.

**Comment by aropan** [comment]
1. `Global rank` can be interpreted as rank for all accounts, not only special resource. So `rank` for `account` is rank of resource. And I think it more clear.  
Left most column isn't rank. This just row number, so when we sort by rating and filter by country the column interpreted as country rank.

2. `Rank` and `Global Ranking` may be different - `Rank` calculated by accounts and ratings on clist, `Global Ranking` value from leetcode during account parsed.

**Comment by manoharreddyporeddy** [comment]
Thanks for details provided.

===

When I am here   https://clist.by/resource/leetcode.com/?country=IN
I am seeing country india dashboard

When I click on "Top rating" 1st icon
I go to another page
but the country india filter is removed
( this is unexpected, filter shud continue to exist as I move across pages ideally, this might be a bug )

Here Rank I assumed is global (non country) for leetcode ( because only leetcode filter exists )  ( like 48 for 1st row )
then I add a filter india again, clearly on left, all flags are same country so all good
Again when adding Global ranking shows a different rank ( like 50 for 1st row )

But neither 48 or 50 is rank of pathetic-dog ( 1st row )
it is 52 (52/440,831 Global Ranking) as seen at https://leetcode.com/pathetic-dog/
Hence the confusion.

The 48 vs 50 vs 52 might be a bug as well ( as only 1 resource / Leetcode is selected )
https://clist.by/accounts/?search=&sort_column=rating&sort_order=desc&country=IN&resource=102&field=

Additionally, for leetcode, "Global Ranking" is given at https://leetcode.com/contest/globalranking/
May be, they are differentiating between US vs other domains of leetcode.com vs https://leetcode.cn/

So a clear column name (else an Info icon on column) can help either way.

In general,
`Country rank` is within resource like Leetcode for a country
`Global rank(ing)` is within resource like Leetcode across all countries
`CList rank` (or other) can be different, which can be rank for all accounts like Leetcode, Codeforces, etc that are added on CList.

====

So
1 Current `Rank` can be `CList rank` / `Overall rank`.
2, Ideally above rank should same for a person as given in resource page, when only 1 resource is selected in filter above. 2nd bug mentioned above of 48 v s 50 vs 52
3. If filter of country/other is passed along the pages, it will be more smooth experience.

Point 1 is only needed for this issue.
Point 2 & 3 are good to have.

Thanks for your time on these issues @aropan

**Comment by aropan** [comment]
1. But there isn't `Country rank` column. It is just row number column.If I added a `Country rank` column, then it would be necessary to specify specific name for `Rank` field. Now I don’t think there is a need for this.

2. Yeah, the difference is normal. Parsing rating from leetcode.com need a long time. Updating leetcode account information also unreliable. Column `Rank` isn't calculatable column and recalculated with a delay.

3. I'll add.

**Comment by manoharreddyporeddy** [comment]
1 Still feel "Rank" can be "Overall rank" as its combined rank ( Not related to country rank at all ).
But rank is also ok for now.

2 Ya, minor diff is all good.

3 Thanks, it will help.

**Comment by aropan** [comment]
Ok, renamed. And fixed urls to pass country filter.

**Comment by manoharreddyporeddy** [comment]
Thanks for your time & hardwork @aropan . Really appreciate it.
