### ISSUE TITLE
Robocontest.uz upsolve feature

### ISSUE THREAD

**Issue by Asadbek525** [aropan/clist#273]
Robocontest.uz upsolve feature has been added

**Comment by aropan** [comment]
Do you mean submissions in attempts pages (as example https://robocontest.uz/olympiads/796/attempts)?
Can I see upsolved tasks for set user? As example as here https://robocontest.uz/profile/dxz05, but there isn't all tasks in page.

**Comment by aropan** [comment]
Done. Upsolving will be available when updating contests or linked accounts.
