### ISSUE TITLE
Navigation from profile to country ratings

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#275]
@aropan thanks for the hard work you put in on clist website

===

When I am on profile page
for example, here https://clist.by/account/pathetic-dog/resource/leetcode.com/
By clicking on below icon
I should be able to go back to that country all ratings, that is, this page https://clist.by/resource/leetcode.com/?country=IN

![image](https://github.com/aropan/clist/assets/8236389/94e6e445-00ce-4564-94ea-49c3ace3babb)

**Comment by aropan** [comment]
Fixed.
