### ISSUE TITLE
Unable to see rating due to its blue color on black background

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#276]
Thanks for your hard work on this website @aropan 

===

A minor but important color change request is below.

When I am in profile page
for example, here https://clist.by/account/pgmreddy/resource/leetcode.com/
and i hover a rating point, the popup comes up, and that popup is in light black background, and we cannot see blue color on it.
![image](https://github.com/aropan/clist/assets/8236389/9ec1060a-5ab0-4799-9074-c07d2b9b8e10)

May be background can be white or other, and so all colors can be visible clearly,
Or
Just the rating part of 1771 can have a background color of white.

**Comment by aropan** [comment]
Fixed to use lighter rating color.
<img width="244" alt="image" src="https://github.com/aropan/clist/assets/1968460/390bea31-2d22-4c17-a29a-f65c38537b9d">
