### ISSUE TITLE
Question is renamed - Q2 of Weekly Contest 29

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#279]
@aropan  thanks for your work on this website

===

When we are at https://clist.by/standings/weekly-contest-29-12003144/
Clicking on Q2, takes us to 'Page Not Found' page

Its renamed
from https://leetcode.com/contest/leetcode-weekly-contest-29/problems/array-partition-i/
to___ https://leetcode.com/contest/leetcode-weekly-contest-29/problems/array-partition/

Note that leetcode contest has correct for Q2 https://leetcode.com/contest/leetcode-weekly-contest-29/

===

**Comment by aropan** [comment]
Fixed.

**Comment by manoharreddyporeddy** [comment]
Website is down
![image](https://github.com/aropan/clist/assets/8236389/b1908ae4-e3f4-47f9-9da6-32fbd03bfeaa)

@aropan
