### ISSUE TITLE
Question is renamed - Q2 of Weekly Contest 179

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#280]
Thanks for your work on the clist website @aropan 

===

Unable to search for a problem at
https://clist.by/problems/?search=&resource=102&contest=18335391&status=&chart=&sort_order=desc&sort=

Reason:

https://leetcode.com/contest/weekly-contest-179/problems/bulb-switcher-iii/
is renamed to
https://leetcode.com/contest/weekly-contest-179/problems/number-of-times-binary-string-is-prefix-aligned/

Please fix the link & name

Diff Screenshot:

https://clist.by/problems/?search=&resource=102&contest=18335391&status=&chart=&sort_order=desc&sort=
![image](https://github.com/aropan/clist/assets/8236389/201226ee-2bc1-4fa8-81e2-3e138fe3ba1d)

https://leetcode.com/contest/weekly-contest-179/
![image](https://github.com/aropan/clist/assets/8236389/e38790d5-9a22-45a5-a1e3-7a439ebce9ee)

===

**Comment by manoharreddyporeddy** [comment]
In other words:

At https://leetcode.com/contest/weekly-contest-179
Q2 is https://leetcode.com/contest/weekly-contest-179/problems/number-of-times-binary-string-is-prefix-aligned

At https://clist.by/standings/weekly-contest-179-18335391/
Q2 is https://leetcode.com/contest/weekly-contest-179/problems/bulb-switcher-iii

Note that leetcode contest has correct link for Q2

===
jfyi - @aropan

**Comment by aropan** [comment]
I am waiting to resolve my support ticket in support.leetcode.com.

**Comment by manoharreddyporeddy** [comment]
ty

**Comment by aropan** [comment]
From support:
_...I'll inform you when our content team fixed this issue..._

**Comment by manoharreddyporeddy** [comment]
Its ok, this can stay open for more time.
( If we close this someone else open on the same )

**Comment by aropan** [comment]
Fixed.
