### ISSUE TITLE
Show rank / N for logged in user, on Top rating on resource page

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#284]
Thanks for the hard work you put on clist website, @aropan 

===

At https://clist.by/resource/leetcode.com/
Please add rank or N for logged in user at highlighted position in below screenshot:

![image](https://github.com/aropan/clist/assets/8236389/63da72ef-04a3-484a-a764-2d53806609e1)

**Comment by aropan** [comment]
Implemented.

**Comment by aropan** [comment]
Just like here https://dev.clist.by/resources/top/.

**Comment by manoharreddyporeddy** [comment]
> Just like here https://dev.clist.by/resources/top/.

They really look great https://clist.by/resources/top/
Thank you
