### ISSUE TITLE
Show logged in user line on Accounts page

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#285]
Thanks for the hard work you put on clist website, @aropan 

===

At https://clist.by/accounts/?resource=102&sort_column=rating&sort_order=desc&country=IN
Please add logged in user line,  similar to below one, on top/bottom, so it stays fix when we scroll

At https://clist.by/standings/weekly-contest-346-43330383/
We can see logged in user line, fixed at the bottom even when we scroll

![image](https://github.com/aropan/clist/assets/8236389/b58034bb-bbda-498e-b42b-3ec64377ebdd)

**Comment by aropan** [comment]
Done.
