### ISSUE TITLE
Yesterday, Today & Tomorrow - 3 day view for calendar

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#286]
Thanks for the efforts you put in on this website @aropan 

===

Homepage calendar at https://clist.by/?view=calendar is not so good

Today is now currently disabled
default view is total month ( the x marked is past weeks )
but we are generally interested in just today ( the ticket marked in screenshot ) or recent completed or just about to happen

===

We generally are not interested in past contests at all
especially more than 1 day back

===

1 Ideally default view should show 3 days view ( instead of 7 days view )
It should just show 1 Yesterday ( to left ) 2 Today (in middle ) & 3 Tomorrow ( to right )

2 Also for example, full list of Today's contests should be shown, vertically by default, not when we click on "more" link.

3 Other views of weekly, month, etc can exists but point 1 can be default ( which is hot => happening now / just happened in last 24 hours / going to happen in next 24 hours ).

===

![image](https://github.com/aropan/clist/assets/8236389/a28a3561-2172-4ced-b251-f0e3e844298d)

**Comment by aropan** [comment]
* `today` button is return to today state if you're scrolling through the calendar.
* if you want one day back only then use this option in [preferences](https://clist.by/settings/preferences/):
<img width="280" alt="image" src="https://github.com/aropan/clist/assets/1968460/e4b8f929-8bdb-4d5b-94da-f8f956af2b29">
* I think about new UI viewing for calendar (yesterday, today, tomorrow).

**Comment by aropan** [comment]
I configured [filters](https://clist.by/settings/filters/) and my calendar looks like:

<img width="1523" alt="image" src="https://github.com/aropan/clist/assets/1968460/9ed5e8b2-4c22-4ca2-aeee-add8c15e0b76">

**Comment by manoharreddyporeddy** [comment]
> I configured [filters](https://clist.by/settings/filters/) and my calendar looks like:
> 
> <img alt="image" width="1523" src="https://user-images.githubusercontent.com/1968460/275336089-9ed5e8b2-4c22-4ca2-aeee-add8c15e0b76.png">

This view is better looking, all contests opened already.
It will be great if you can make this as default for all.

**Comment by manoharreddyporeddy** [comment]
> * I think about new UI viewing for calendar (yesterday, today, tomorrow).

Yes
Please think about new UI viewing for calendar (yesterday, today, tomorrow).

My friends want the same too. Just 3 days as default. ( or, 3 near-by days, if there are no contests today, for example, then 1 day in past, 2 days in future. This can be enhancement to come later. )

**Comment by manoharreddyporeddy** [comment]
> * `today` button is return to today state if you're scrolling through the calendar.
> * if you want one day back only then use this option in [preferences](https://clist.by/settings/preferences/):
> 
> <img alt="image" width="280" src="https://user-images.githubusercontent.com/1968460/275335489-e4b8f929-8bdb-4d5b-94da-f8f956af2b29.png">
> * I think about new UI viewing for calendar (yesterday, today, tomorrow).

3
For easy configuration
the "Past events action in calendar = show/hide/others"
should be in 
on this page only https://clist.by/

**Comment by manoharreddyporeddy** [comment]
jfyi - if possible, 3 day calendar at basic level, something like below, can be helpful:

![image](https://github.com/aropan/clist/assets/8236389/a9425820-088e-4bcf-a2f8-b61acc4b7c31)

1
- Grey text - Already completed contests
- Green text with some background for in-progress contests - highlight to say that we are at this time
- Blue text - future contests

2
For each contest line, there can be second line
- this additional line can show, start time, end time, how much is left before contest ends ( decreasing contest duration )
  - this line will be helpful to user to decide whether to join contest or not
    - ( example: if contest started and its only 5 mins delay, user might join that contest )

@aropan

**Comment by aropan** [comment]
I'll leave this version for now:

![image](https://github.com/user-attachments/assets/dec855fa-9dc1-42d3-aaf3-6101923b67df)

**Comment by manoharreddyporeddy** [comment]
Sure
its better

Week - was showing more past days
5 days - is showing more future days

===

If possible, please fix below UI issue

Once we select week, it looks like below - as if both 5 days & week is selected

![image](https://github.com/user-attachments/assets/6e21c47a-2723-484c-9275-d4d2a29735b4)

**Comment by aropan** [comment]
Fixed.
