### ISSUE TITLE
Previous Versus bookmarks are not working now

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#287]
Thanks for the hard work you put in on clist website @aropan 

===

I have 10+ bookmarks, based on whom I connected on linkedin, etc, etc

An example below:
https://clist.by/versus/lc:awasthishubh/vs/lc:computationlan/vs/lc:ajna2/vs/pgmreddy/vs/lc:petersburg/vs/lc:claytonjwong/vs/lc:samir70/vs/lc:parassidhu/vs/lc:nimit95/vs/lc:ajna/vs/lc:deepakandgupta/vs/lc:aanchii/vs/lc:venkateshwar1996/vs/lc:bhawna_b/

Above kind of bookmarks are showing the below error now
it may be because there is no redirect happening as discussed at https://github.com/aropan/clist/issues/281#issuecomment-1756113353

![image](https://github.com/aropan/clist/assets/8236389/494d0109-cd8c-4484-a4c5-705fcc20ef3d)

**Comment by aropan** [comment]
Edited messages and added redirect.

**Comment by manoharreddyporeddy** [comment]
Thanks a lot for this. All bookmarks are working perfectly. @aropan
