### ISSUE TITLE
Important - Unable to add Leetcode account

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#288]
Thanks for hard work you put in on clist website @aropan 

====

This is important I think

Since accounts are changed to .com and .cn ( below )
https://github.com/aropan/clist/issues/287
https://github.com/aropan/clist/issues/281#issuecomment-1756113353

Most probably
new account additions post clist registration for leetcode would have dropped at lot

The reason is below - Unable to add Leetcode account ( pgmreddy ) - as we know nobody adds pgmreddy@.com as required
Please fix this so registration will be useful when leetcode users join clist via account addition.

![image](https://github.com/aropan/clist/assets/8236389/44db8fee-ff55-47f4-b992-a7522661a725)

===

Possibly some other important URLs are also affected along with above add account page
So if possible verify all pages once - esp for leetcode related ones

**Comment by aropan** [comment]
I think in this case you can use advanced search and find you account. Is not it so?

**Comment by manoharreddyporeddy** [comment]
Oh. I have not seen Advanced Search till today :)

may be because
- "Add" button worked at that time.
- Also Add is blue color (easily seen), other button is white

I would think "Advanced Search" in general is for Advanced users, so normal users won't use it.

Yes, Advanced Search works, but people won't notice or use it much ( similar as Google Advanced Search )
All normal users would generally expect Add would work ( similar as Google Search button )

Ease of use rule is users would come back to website, when things are easy on website ( similar to https://github.com/aropan/clist/issues/286 - 3 day calendar is super useful )

**Comment by aropan** [comment]
Fixed.

https://github.com/aropan/clist/assets/1968460/e1e7633d-afa6-4043-b27c-78e00c04f6df

**Comment by manoharreddyporeddy** [comment]
perfect
