### ISSUE TITLE
Search timesout sometimes

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#289]
While doing search, it timesout
I have below 2nd URL below as bookmarked which timesouts today. ( possibly worked earlier ). It has only 35 some mostly random users.

1
pass
https://clist.by/accounts/?search=pgmreddy%20||%204_intrvw%20||%20Petersburg%20||%20aanchii%20||%20ajna2%20||%20awasthishubh%20||%20awice%20||%20balakrishnan_v%20||%20bhawna_b%20||%20claytonjwong%20||%20computationlan%20||%20contester1%20||%20deepakandgupta%20||%20goodgreater%20||%20henrychen222%20||%20l1ne%20||%20neal_wu%20||%20newRuanXY%20||%20nimit95%20||%20numb3r5%20||%20parassidhu%20||%20pathetic-dog%20||%20paultman%20||%20peehs_moorhsum%20||%20penguinhacker%20||%20petersburg%20||%20razorsharp7%20||%20runnerIo%20||%20samir70%20||%20samyak1409%20||%20sanjanapeter%20||%20venkateshwarreddyr%20||%20votrubac&sort_column=rating&sort_order=desc&resource=102

2
timeout
https://clist.by/accounts/?search=pgmreddy+%7C%7C+4_intrvw+%7C%7C+Petersburg+%7C%7C+aanchii+%7C%7C+ajna2+%7C%7C+awasthishubh+%7C%7C+awice+%7C%7C+balakrishnan_v+%7C%7C+bhawna_b+%7C%7C+claytonjwong+%7C%7C+computationlan+%7C%7C+contester1+%7C%7C+deepakandgupta+%7C%7C+goodgreater+%7C%7C+henrychen222+%7C%7C+l1ne+%7C%7C+lee215+%7C%7C+math1000+%7C%7C+math1122+%7C%7C+neal_wu+%7C%7C+newRuanXY+%7C%7C+nimit95+%7C%7C+numb3r5+%7C%7C+parassidhu+%7C%7C+pathetic-dog+%7C%7C+paultman+%7C%7C+peehs_moorhsum+%7C%7C+penguinhacker+%7C%7C+petersburg+%7C%7C+razorsharp7+%7C%7C+runnerIo+%7C%7C+samir70+%7C%7C+samyak1409+%7C%7C+sanjanapeter+%7C%7C+venkateshwarreddyr+%7C%7C+votrubac&sort_column=rating&sort_order=desc&resource=102

![image](https://github.com/aropan/clist/assets/8236389/8a5900c1-7b55-4cf2-977d-b05d3a17c447)

**Comment by aropan** [comment]
Why are you using these queries?

**Comment by aropan** [comment]
I added list filter in the Accounts page. Use it https://clist.by/settings/lists/.

**Comment by manoharreddyporeddy** [comment]
> Why are you using these queries?

I searched for some connects on linkedin, and few others.

For example - yours & mine:
https://clist.by/accounts/?search=pgmreddy+%7C%7C+aropan&resource=102

![image](https://github.com/aropan/clist/assets/8236389/8dfbfe25-3c22-4474-b399-fe360fa69882)

Found the results interesting
So, saved the URL as bookmark.
Mostly others might do too.

**Comment by manoharreddyporeddy** [comment]
I created a list

https://clist.by/list/a417ea34-3ddf-4fab-8802-8437626d23d3/
![image](https://github.com/aropan/clist/assets/8236389/df6e99a0-40aa-413f-8794-d70fa39613ce)

Only option i can do is Vs, so I did Vs:
https://clist.by/versus/pgmreddy/vs/uwi/vs/aropan/

it shows like below:
![image](https://github.com/aropan/clist/assets/8236389/e165cc22-91ec-46cf-a267-5cfee764f4df)

Above is a lot different than the search view ( which is a list view )
![image](https://github.com/aropan/clist/assets/8236389/7737f6a9-1a5f-4f62-85b9-cac1a1b4c21a)

========

So I think

1 Search view ( list ) is totally different from Vs view ( graphs )
So both views are different & important

2 If you want to redirect some traffic to lists so Vs can be used
Then we can add link to lists on top right corner like below

![image](https://github.com/aropan/clist/assets/8236389/ab6dff18-452b-4876-a727-ab0c198d871f)

If possible, please check if 1 & 2 can be addressed

**Comment by manoharreddyporeddy** [comment]
I added point 3 above.

**Comment by aropan** [comment]
1.

<img width="238" alt="image" src="https://github.com/aropan/clist/assets/1968460/992b8642-3480-4def-ab00-6582db7ee217">

3.

<img width="249" alt="image" src="https://github.com/aropan/clist/assets/1968460/e2bb73dd-230e-4d2c-b9ac-03fa066e33bf">

**Comment by manoharreddyporeddy** [comment]
Thanks for the hardwork on website @aropan 

===

Below works fast

1 Create list
2 Use it in Search

![image](https://github.com/aropan/clist/assets/8236389/e422dd8e-def9-44da-af72-7dc8c225d805)

===

However Lists are not easily accessible still
because Menus on top right are least accessed.

So Lists ( since search is slow & times out ) must be the 1st item, like shown below:

![image](https://github.com/aropan/clist/assets/8236389/48c21ae9-69ef-4dca-99d6-dcbde25d6c92)

If Lists are 1st, it hints that its better to use Lists for speed
However Account box is bigger most users will still use search box only. So no issues in making Lists as 1st item.

**Comment by manoharreddyporeddy** [comment]
@aropan
If possible, please check if this icon movement to front

**Comment by aropan** [comment]
Added a little hint.

<img width="489" alt="image" src="https://github.com/aropan/clist/assets/1968460/3230852f-071b-4eab-a8e7-eadabbc30e4f">
