### ISSUE TITLE
Change to button with "Add" text

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#290]
Thanks very much for your work on clist @aropan 

===

At https://clist.by/accounts/?add_account=on&resource=102&search=pgmreddy

Please change
from button with Add icon ( ![image](https://github.com/aropan/clist/assets/8236389/099cb254-fed4-4eae-b203-9dbf9465f99f) )
to button with Add text ( ![image](https://github.com/aropan/clist/assets/8236389/bfc1a5e7-4554-45ca-a76b-1714ba3aaeb0) )

Since Add button does not work easily, some may go to Advanced Search, then it will be easy to see button with "Add" text. Add with icon is not easy to use or see as it is too small.

![image](https://github.com/aropan/clist/assets/8236389/0c64fc3e-2cd9-4990-917e-074c31bda2f1)

**Comment by aropan** [comment]
Added tooltip.
