### ISSUE TITLE
Add Start time, Start/End Time is confusing

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#291]
Thanks for the work you put in on clist @aropan 

====

At https://clist.by/?view=list

Right now `Weekly Contest 368` contest is still running
![image](https://github.com/aropan/clist/assets/8236389/02a434dc-97df-424d-9d68-59556237c63a)

The `Start/End Time` is not so useful.
It is confusing, if it is Start time or End time.
For leetcode it is `End Time` after contest has started

Even if it is by design that you will show Start time before the contest, and End time after the contest has started. This is still confusing. Once I see start time, it should stay start time only.

End time is not more useful than Start time. Already `Time Left` is there

Please add Start time
OR
Please add Start time & End time as two separate columns.

**Comment by aropan** [comment]
If the event has started, I want to know the exact time the event will end. Because I want to schedule time before that deadline to participate. I think the start time is not important information - it has already passed.

**Comment by aropan** [comment]
I did some changes to better understand start and end times:

<img width="1572" alt="image" src="https://github.com/user-attachments/assets/839f1f8e-a0ba-478a-a864-0ccfa8ede524">

**Comment by manoharreddyporeddy** [comment]
perfect
