### ISSUE TITLE
Accounts page - Rename Overall Rank to Rank 

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#292]
Thanks for the hard work you put in on clist website @aropan 

===

At https://clist.by/accounts/

Rating seems to be single account based like leetcode
So Rank is also single account based like leetcode

1
But it is named Overall Rank
It should be just "Rank"

2
If Overall Rank is added, then it should be average of all ranks of all accounts - at a coder level.
Also "Average Rating" is good to have, equals average of all ranks of all accounts - at a coder level

![image](https://github.com/aropan/clist/assets/8236389/f9f357a4-cc5d-4ee8-a8f2-e1cabff70b4a)

===

**Comment by aropan** [comment]
Fixed. Renamed `Resource rank`.
