### ISSUE TITLE
Accounts page - Default sort can be Rank ascending at account level + Avg rating at coder level

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#293]
Thanks for the hard work you put in on clist website @aropan 

===

In Accounts page - Default sort should be Rank Ascending
https://clist.by/accounts/?sort_column=overall_rank&sort_order=asc

If multiple Ranks are same like 1st rank, then Average Rating at a coder level can be used.

So default sort can be
1 Rank ascending at account level
+
2 Avg rating at coder level

![image](https://github.com/aropan/clist/assets/8236389/3eeeb343-464a-4c7f-a4bc-a705e406af40)

===

This also help when we add a List
then by default the highest rank + avg rating person in that List will go to top.

===

**Comment by aropan** [comment]
Resource rank (before was overall rank) can't compare different resource. This makes little sense. And average rating too - difference resources have different rating scales.

**Comment by manoharreddyporeddy** [comment]
Overall rank is not overall but resource-specific.

Alright.

Best regards, M

=======

![image](https://github.com/user-attachments/assets/536568ee-b70b-4b57-b04d-63440145885a)
