### ISSUE TITLE
Lists visibility - Public vs Private

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#294]
Thanks for the hard work you put in on clist website @aropan 

===

Anyone can see ( public ) the List
https://clist.by/list/a417ea34aaaaaaaaaaaaaaaaaaaaaaaaaaa/

However, when List is used in search, no one can see ( private )
https://clist.by/accounts/?search=&list=a417ea34aaaaaaaaaaaaaaaaaaaaaaaaaaa&sort_column=overall_rank&sort_order=asc

I think
1 By default, Both should be private ( no one can see )
2 When List is set to public ( a toggle on List page ) - Then both List and List used in search both should be public ( everyone one can see )

Toggle button on List page can be like below On/Off - Off / Left side is private, On / Right side it public )
![image](https://github.com/aropan/clist/assets/8236389/bd0dfa5a-ae0f-4397-b201-76a183545f66)

**Comment by aropan** [comment]
@manoharreddyporeddy anyone can see if know list url.

**Comment by manoharreddyporeddy** [comment]
@aropan 
Even after knowing the list url - one should not be able to see, because they are some selected group of people.
By default it should be private
When the list is made public, all should be able to see. ( Right now, setting does not exist on clist ) 

This is how the Leetcode lists also works. ( by default all are private, unless made public using toggle setting - with or without knowing list url )

**Comment by aropan** [comment]
I understood. But current version it is middle between private and public - if you don't share list url then anyone can't know about list.

I have already started some edits for this issue. Don't worry.

**Comment by manoharreddyporeddy** [comment]
No worries :)
Just that I shared the list links here, in these issues here :)
I will remove links once the ticket is closed.
All good. Thanks.

**Comment by manoharreddyporeddy** [comment]
jfyi - I changed the list url to   https://clist.by/list/a417ea34aaaaaaaaaaaaaaaaaaaaaaaaaaa/ in all issues.

**Comment by aropan** [comment]
Fixed. Added third option as sharing list to specified coders.

<img width="690" alt="image" src="https://github.com/aropan/clist/assets/1968460/9e826437-5668-40bb-bb0e-3bb9db60b675">

**Comment by manoharreddyporeddy** [comment]
Nice @aropan
Restricted is useful tool ! I will try later.
