### ISSUE TITLE
Problems page - How to filter only non-Premium questions ?

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#297]
Thanks for your hardwork on clist website, @aropan 

===

Leetcode has Premium & non-Premium questions. An example for each is given, at the end below.

How to hide Premium / select only non-Premium questions at below problems page?

https://clist.by/problems/?search=&resource=102&rating_from=0&rating_to=1825&status=noallsolved&chart=&sort_order=asc&sort=rating

With existing Fields, unable to filter non-premium questions. 

====

Premium & non-Premium question examples:

Premium question below, needs Subscribe https://leetcode.com/subscribe/?ref=qd3_pq
https://leetcode.com/problems/find-smallest-common-element-in-all-rows/description/
![image](https://github.com/aropan/clist/assets/8236389/7776000b-b491-4e3f-969b-cc5a47d62791)

Normal question below
https://leetcode.com/problems/sum-of-number-and-its-reverse/description/
![image](https://github.com/aropan/clist/assets/8236389/bf532f43-5012-4dfe-addb-40da7058fa5a)

====

**Comment by aropan** [comment]
Duplicate #400
