### ISSUE TITLE
Standings page - Change `Penalty` to `Finish Time + Penalty`

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#298]
Thanks for features that are coming in on clist - @aropan 

===
At https://clist.by/standings/weekly-contest-369-47240093/

`Penalty` is confusing, I might not have any Penalties like I have no wrong submissions at all, then `Finish Time` is more correct.
But a better name is `Finish Time + Penalty`
So, please change name from `Penalty` to `Finish Time + Penalty`

**Comment by manoharreddyporeddy** [comment]
This is simpler ticket - column name & order change only

**Comment by aropan** [comment]
It's very long and bulky. `Penalty` is general name for parameter to resolved tiebreak on same scores.

**Comment by manoharreddyporeddy** [comment]
Ok

But what about `Finish Time` or `Time` ?

Penalty  in general is -ve meaning:

![image](https://github.com/aropan/clist/assets/8236389/e79acc7e-c0e6-4a0a-a6d6-029ef48b72c5)

**Comment by aropan** [comment]
As you said above, this is not finish time. And I can describe penalty as last success submission time + penalty time, no one can stop me.
