### ISSUE TITLE
Standings page - Column sequence

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#299]
Thanks for the hard work @aropan 

===

In Standings page https://clist.by/standings/weekly-contest-369-47240093/
Current column sequence is below,   but that's not how they occur in time - from start of contest to end of contest & rating come later

![image](https://github.com/aropan/clist/assets/8236389/038c2ade-a1d0-471f-8835-989c998052a2)

Please change to

```
Score	
Penalty
Q1                         ( Follows as they occur in time & easy https://leetcode.com/contest/weekly-contest-369/ranking/ )
Q2
Q3
Q4
Predicted Rating           ( from "Predicted New Rating" )
Predicted Rating Change    ( "Change" should come later - because `Previous rating` column is not shown )
Predicted Rating Perf
Rating                     ( from "New Rating" - because it is current rating now )
Rating Change              ( from "New Rating Change")
```

**Comment by manoharreddyporeddy** [comment]
This is simpler ticket - column name & order change only

**Comment by aropan** [comment]
But `score` and `penalty` will be later than `Q1`, `Q2`, `Q3` and `Q4`? In common it sounds logical, but after the competition it’s no longer so interesting which task was completed when. This way the results on the tasks will be better in the end.

Renaming `New Rating` -> `Rating` is strange. `New rating` means that is rating after this contest and doesn't correspond to the current account rating (now or not).

**Comment by manoharreddyporeddy** [comment]
No :)

1
During wait period ( before the ratings are announced )

it's not natural to have a hole in the table - like below
< some data >  < no data >  < some data > 

2
It should like below ( live chess rating )
That is Rating change is after Rating, not before
( This is because previous / old rating is not there - as told in previous comment ) 

see A
![image](https://github.com/aropan/clist/assets/8236389/66cb8b85-3079-4f73-b3fb-fe7c337a3915)

see B
https://lccn.lbao.site/predicted/weekly-contest-369
![image](https://github.com/aropan/clist/assets/8236389/72959512-33a3-4501-b9cf-65df2992aca4)

3
you can use "New Rating"
when you have "Old Rating" ( we dont have right now )

**Comment by manoharreddyporeddy** [comment]
4
`Predicted New Rating`     is not at all required

because
Predicted already means it is already in future ( which is new one )
So again New is not required at all

`Predicted Rating` is enough & clear in English wise

**Comment by manoharreddyporeddy** [comment]
In other words

When we look at a contest
like at https://clist.by/standings/weekly-contest-345-43118364/

there is no `new rating`
it is just `rating` in that contest

For examples:
What is your rating in Oct 2023 ? - This sounds correct
What is your new rating in Oct 2023 ? - This does not sound correct

**Comment by manoharreddyporeddy** [comment]
Looks like
you already did point 2
I didn't know as there is no ack above
![image](https://github.com/aropan/clist/assets/8236389/9cf790f6-5dec-4fc5-a08a-afc26d5d785b)

Please think about point 1, 3 & 4

**Comment by manoharreddyporeddy** [comment]
Looks like
Point 2 is not consistent

Done example:
https://clist.by/standings/weekly-contest-345-43118364/
![image](https://github.com/aropan/clist/assets/8236389/73c88589-f74f-4205-a47d-d44c605a49e4)

Not done example:
https://clist.by/standings/weekly-contest-369-47240093/
![image](https://github.com/aropan/clist/assets/8236389/8e3f2c51-0c70-4529-8ac0-8ac187f32191)

**Comment by aropan** [comment]
1.

Ratings information more important after contest than result of problem. So this information should be closer to handle column.

2.

No comments.

<img width="889" alt="image" src="https://github.com/aropan/clist/assets/1968460/0cf09911-eed8-4baa-a7b8-6dfeae6b2d7c">

<img width="1194" alt="image" src="https://github.com/aropan/clist/assets/1968460/8d36a5aa-50d6-40f7-8375-1a3e1b48706d">

<img width="1009" alt="image" src="https://github.com/aropan/clist/assets/1968460/d3878cef-64e1-462d-8ab2-7e378a92e99b">

3.

Some contests have "Old Rating" and and the current name is more consistent in general.

4.

I want use "New Rating" in "Predicted" to show connection with "New Rating" and nothing else.

**Comment by aropan** [comment]
2.

Fixed consistent
