### ISSUE TITLE
Reduce information overload - Rating change columns

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#301]
Thanks for your work & time on clist website @aropan 

=============

Rating change as a column is an information overload
We can merge into Rating column and Predicted Rating column

Examples:

![image](https://github.com/aropan/clist/assets/8236389/3bc9f0bb-c3ba-48cf-ac08-4a0e9395b701)

![image](https://github.com/aropan/clist/assets/8236389/dcfbc64c-eec9-4dec-9886-b9ab2c635502)

===

https://clist.by/standings/biweekly-contest-116-46987223/?list=a417ea34-3ddf-4fab-8802-8437626d23d3&neighbors=on
https://clist.by/standings/biweekly-contest-112-45616879/?list=a417ea34-3ddf-4fab-8802-8437626d23d3&neighbors=on

**Comment by aropan** [comment]
Okay, let's try it. Fixed.
