### ISSUE TITLE
Predictions not up after 25 mins post contest

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#302]
Thanks for the work on clist website @aropan 

===

Predictions are not up after 25 mins post contest

https://clist.by/standings/weekly-contest-370-47459261/

![image](https://github.com/aropan/clist/assets/8236389/a4b88585-e875-4145-bd09-6b3693b76485)

===

while others are up already

https://lccn.lbao.site/predicted/weekly-contest-370

![image](https://github.com/aropan/clist/assets/8236389/12b8d717-9dd8-4dc4-a35f-4cb0b221036a)

===

Predictions are seen just after the contest, it should be up asap, otherwise not so useful

**Comment by aropan** [comment]
Fixed.
