### ISSUE TITLE
Standings page - Weekly Contest 371 - Missing users

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#305]
Thanks for the work on clist @aropan 

===

Yesterday's contest
Works fine - gives 2 results
https://clist.by/standings/biweekly-contest-117-47614333/?search=JOHNKRAM+%7C%7C+venkateshwarreddyr
![image](https://github.com/aropan/clist/assets/8236389/fcbfeb0b-4349-4657-b3df-95bc7f854057)

Today's contest
Does not work - gives 1 result only
https://clist.by/standings/weekly-contest-371-47614332/?search=JOHNKRAM+%7C%7C+venkateshwarreddyr
![image](https://github.com/aropan/clist/assets/8236389/0d77e13c-2c13-4f53-8d35-5d04c2ef456d)

However 2nd user has rank can be seen here
https://leetcode.com/contest/weekly-contest-371/ranking/161/
![image](https://github.com/aropan/clist/assets/8236389/19d41091-bdfc-4bb6-acb0-073aa0046043)

**Comment by aropan** [comment]
Fixed. Reupdated.
