### ISSUE TITLE
The Ranking for Country in Hacker Earth Does not work, at least for Colombia

### ISSUE THREAD

**Issue by niquefa** [aropan/clist#307]
https://clist.by/resource/hackerearth.com/?country=CO&period=all

https://www.hackerearth.com/leaderboard/contests/rated/?country=CO

**Comment by aropan** [comment]
<img width="1090" alt="image" src="https://github.com/aropan/clist/assets/1968460/d01cea2b-98dd-48f1-a69e-114751ea0d08">

May be do you know why [Reshab Gupta](https://www.hackerearth.com/@coolreshab) has country Columbia?

**Comment by niquefa** [comment]
@aropan I have no Idea, it appears in his profile to be from Bangalore which is clearly not from Colombia.

**Comment by aropan** [comment]
I fixed it as much as possible. Thanks for catching that!
<img width="508" alt="image" src="https://github.com/aropan/clist/assets/1968460/93ec6ceb-0481-4e7d-a38f-73d92e19760f">
