### ISSUE TITLE
Calendar view - Today highlight color, is barely visible

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#308]
Thanks or the work on clist @aropan 

===

Please enhance the color for Today
From looks like light orange
To something brighter ( at least double the existing color, may be)

![image](https://github.com/aropan/clist/assets/8236389/4b638bbf-045f-437a-b52e-0bb98a464d38)

**Comment by aropan** [comment]
Fixed.

<img width="1531" alt="image" src="https://github.com/user-attachments/assets/56589813-64ff-4b08-ad6f-f767cffd6393">
