### ISSUE TITLE
Code page - Add Update button

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#310]
Thanks for the work on clist @aropan 

===

When we click on Top Right corner
it take us to coder page - example - https://clist.by/coder/pgmreddy/

The status of Update progress ( spinning can be seen here )
However we need to go to Account profile to manually trigger Update button
For example https://clist.by/account/pgmreddy@.com/resource/leetcode.com/

We should be able to Update from Coder page also for ease.

Please enable Update from coder page also, it saves a click, a bit of user & server time
![image](https://github.com/aropan/clist/assets/8236389/b0aa0e7c-e190-44f4-8303-f4076059a119)

**Comment by aropan** [comment]
Fixed.
