### ISSUE TITLE
Standings page - Predicted New Rating is wrong

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#311]
Thanks for your work on clist, @aropan 

===

1
`Predicted New Rating` looks wrong
It does not consider `Current Contest Rating` as 1669
see https://leetcode.com/venkateshwarreddyr/

2
Adding `Current Rating` column might help

3
`Predicted New Rating Change` is not matching other websites

Link1
https://clist.by/standings/biweekly-contest-118-47780244/?search=venkateshwarreddyr&detail=true

Link2
https://lccn.lbao.site/predicted/biweekly-contest-118
User - venkateshwarreddyr

![image](https://github.com/aropan/clist/assets/8236389/8c628c17-041b-418e-943a-a2f832b11df2)

**Comment by aropan** [comment]
This account was updated only after contest. Before rating prediction was calculated with `Weekly Contest 370`:

<img width="1093" alt="image" src="https://github.com/aropan/clist/assets/1968460/03de36b0-9ada-497b-b3ac-5264a6bce2d2">

It works after updating account and after repeat calculating rating prediction. These steps are ran automatically and just have to wait.

**Comment by aropan** [comment]
Fixed.

<img width="1248" alt="image" src="https://github.com/aropan/clist/assets/1968460/d2063f04-c024-4de1-ae7f-6f4b10242c74">
