### ISSUE TITLE
Delete data about me held by clist.by

### ISSUE THREAD

**Issue by katre** [aropan/clist#312]
I do not have a user account. I will not create a user account.

Someone on a private [Advent of Code](adventofcode.com) leaderboard sent me a link to our leaderboard, with data ingested to clist.by. This includes my information, such as my username and my progress on the Advent of Code challenges.

This information appears to be publically available on your site.

Please delete all data referring to my account (katre@github.com) and no not continue to scrape or display it.

[Your privacy policy](https://clist.by/privacy/) is entirely focused on user accounts and does not account for user data you have collected for people who do not have accounts. You should update it accordingly.

**Comment by aropan** [comment]
Deleted.
