### ISSUE TITLE
Feature Request - UI of contest graph 

### ISSUE THREAD

**Issue by anuragdw710** [aropan/clist#313]
<img width="602" alt="image" src="https://github.com/aropan/clist/assets/78266752/3cd9d39f-de97-49ce-b3d5-a976cee555a9">
This UI for combining graphs of contests can be implemented, which seems good as most users don't scroll all the graphs.

**Comment by aropan** [comment]
@anuragdw710 where did you get this graph?

**Comment by anuragdw710** [comment]
https://www.stopstalk.com/user/profile/hydra_cody

**Comment by aropan** [comment]
Added.

https://clist.by/coder/hydra_cody/

<img width="751" alt="image" src="https://github.com/user-attachments/assets/c52e9c80-1353-4984-a329-5b803e5bdedd">
