### ISSUE TITLE
Unrated Participants in CodeChef Starters

### ISSUE THREAD

**Issue by nskybytskyi** [aropan/clist#318]
Some CodeChef Starters are only rated until a certain rating, like [Starters 117 (Rated till 5-Stars)](https://www.codechef.com/START117). After the contest, CodeChef removes unrated participants from the [ranklist](https://www.codechef.com/rankings/START117A). Clist then pulls this final ranklist and also removes unrated participants.

It is undesirable because:
- it is inconsistent with other platforms like CodeForces or AtCoder;
- it messes up stats such as number of contests;
- it makes tracking [solved problems](https://clist.by/problems/) unnecessarily complicated.

I propose the following solution: if the latest ranklist doesn't contain some participants, keep their previous available records. It shouldn't mess anything up because CodeChef contests are full-feedback and there is no hacking. Even plagiarised accounts are moved to the last place instead of being completely removed from the ranklist.

**Comment by aropan** [comment]
I resolved issue with tracking problems.

Keep previous available records have more inconsistent (because how get previous records for past contests and more unstable (parser will not have time to get uncut results). I don't plan to change anything yet.
