### ISSUE TITLE
504 Gateway Time-out - many times

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#319]
Thanks for your work @aropan 

===

Below is constant problem just after the contest more times, also when the contest is not running - if possible, can be improved

https://clist.by/
https://clist.by/standings/weekly-contest-381-49157447/
https://clist.by/standings/weekly-contest-381-49157447/?search=&list=a417ea34-3ddf-4fab-8802-8437626d23d3

![image](https://github.com/aropan/clist/assets/8236389/8e491b4d-d5a6-49a3-99fa-65d4eca092b1)

![image](https://github.com/aropan/clist/assets/8236389/c7edf36e-62f3-46b6-9a9f-61f2bd16574f)

===

may be, below are options:

1 one way to improve might be cacheing like redis, etc - might be costly

2 another one might be create an alternate table to store calculated results & search from those DB tables - ( while main tables are busy to get updated information from leetcode )

**Comment by aropan** [comment]
Issue was big values of iowait. 

Past:
![telegram-cloud-photo-size-4-5897635760297854491-y](https://github.com/aropan/clist/assets/1968460/c771b231-8940-42d4-bab2-21b636837794)

Now:
<img width="1202" alt="image" src="https://github.com/aropan/clist/assets/1968460/4a964bc5-19e4-43b1-8c27-015becc96753">

Everything should be fine now.

**Comment by manoharreddyporeddy** [comment]
Links are opening immediately now. Wow! Perfect.
