### ISSUE TITLE
Problems page - Filter with negation

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#320]
Thanks for the work on clist @aropan 

===

works:
problems with
backtracking and dynamicprogramming   ( &tag=82&tag=24 )
https://clist.by/problems/?search=&resource=102&field=short&field=key&rating_from=0&rating_to=5000&favorite=on&favorite=off&status=noallsolved&chart=&sort_order=asc&sort=rating&tag=82&tag=24

does not work:
problems with
backtracking and not dynamicprogramming  ( &tag=82&tag=-24 )
https://clist.by/problems/?search=&resource=102&field=short&field=key&rating_from=0&rating_to=5000&favorite=on&favorite=off&status=noallsolved&chart=&sort_order=asc&sort=rating&tag=82&tag=-24

1 if above 2nd one ( or, similar exclusion ) is possible, it will be of excellent use
2 if there is a UI option, even better
3 if can be applied to other pages, where applicable, it will help too

**Comment by aropan** [comment]
`&tag=82&tag=24` worked as  `backtracking OR dynamicprogramming`. Fixed to `backtracking and dynamicprogramming` (more popular case).

For `backtracking and not dynamicprogramming` try to use search query `tag:backtracking && ! tag:dynamic programming` [here](https://clist.by/problems/?search=tag:backtracking+%26%26+!+tag:dynamic+programming&groupby=tag).

**Comment by manoharreddyporeddy** [comment]
Thanks @aropan

Below link works:
https://clist.by/problems/?search=tag%3Abacktracking+%26%26+%21+tag%3Adynamic+programming&status=&chart=&sort_order=desc&sort=
