### ISSUE TITLE
Account page - Unstable sort

### ISSUE THREAD

**Issue by nskybytskyi** [aropan/clist#323]
Here is a list of the recent competitions on [my profile page](https://clist.by/coder/Sky_Nik/) (potentially outdated by the time you read this issue):

<img width="746" alt="Знімок екрана 2024-02-06 о 05 24 17" src="https://github.com/aropan/clist/assets/25816558/b33cf95c-c84c-45f9-ac61-48d074cdeb2f">

Nothing is wrong so far. However, when I click on "more", I sometimes get the following unexpected result:

<img width="754" alt="Знімок екрана 2024-02-06 о 05 19 49" src="https://github.com/aropan/clist/assets/25816558/afe5b77e-4742-4066-a81b-601a89e38e8d">

As you can see, Codeforces Round 921 (Div. 1) appears twice. If you refresh the page several times, you may also get other results, such as Div. 2 appearing twice: 

<img width="759" alt="Знімок екрана 2024-02-06 о 05 17 55" src="https://github.com/aropan/clist/assets/25816558/1a5fd17d-0b2a-4dff-969c-11873fa8ecb3">

Sometimes, you also get expected results (Div. 1 and Div. 2 or Div. 2 and Div. 1).

I suspect that it happens because:
- you sort contests by start/end time using an unstable sorting algorithm;
- I "participated" (live and upsolving) in two contests with the same start/end time;
- every time I press "more" the list is sorted anew, and a slice is returned;
- these contests happened to be on the boundary around "more".

For example, if `sorted` was unstable, then both `sorted(a)[:10]` and `sorted(a)[10:100]` are always valid responses for the corresponding slice, but `sorted(a)[:10] + sorted(a)[10:100]` is not necessarily a valid response for `sorted(a)[:100]`.

**Comment by aropan** [comment]
I hope I've fixed this.
