### ISSUE TITLE
High load time of contest graph data of users

### ISSUE THREAD

**Issue by anuragdw710** [aropan/clist#325]
**High load time of contest graph data of users**
- While opening the user profile there is a high load time for graph data. There is no need to load all the previous contest graph details at the beginning of the page load.

- One possible solution can be to load only the data that the user needs. Make points on the graph and load other details as clicks on particular points on the graph.

<img width="478" alt="image" src="https://github.com/aropan/clist/assets/78266752/5761c490-d547-4efd-aa30-2ab4d188fffe">

**Comment by aropan** [comment]
How long is it?

I see close to 1 second.

<img width="1537" alt="image" src="https://github.com/user-attachments/assets/0ef27590-4d56-456d-8c84-058b82145fdb">

**Comment by aropan** [comment]
Sometimes CLIST have problem with intensive load. Let me know if the issue is still relevant.
