### ISSUE TITLE
Profile > Lists - Lists have duplicate, and can have order

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#326]
Thanks @aropan  for your work on clist

=====

Profile Lists have duplicate entries
. When we insert again, these can be ignored with yellow message  (red fail, green pass)
. When we insert, it has be added at end, however after refresh its better to see in ascending order by default
In other words, duplicate need not be inserted, "Ascending order" will help ( another "Insertion order" can also exists like in instagram )

Example link
https://clist.by/list/a417ea34-3ddf-4fab-8802-8437626d23d3/

SS
![image](https://github.com/aropan/clist/assets/8236389/f6847111-7c2e-480d-aa36-ef134e2cbe5d)

**Comment by aropan** [comment]
Fixed.

**Comment by manoharreddyporeddy** [comment]
Perfect, looks good now, thanks @aropan 

For order, I raised another issue, its good to have, when you have time - https://github.com/aropan/clist/issues/328
