### ISSUE TITLE
Standings page > Not live today

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#327]
Thanks for your work on clist, @aropan 

===

In previous week contest, it was live contest
I could see ranking of players as they happen

but today, it only displays "No standings"

https://clist.by/standings/biweekly-contest-124-49565530/?list=a417ea34-3ddf-4fab-8802-8437626d23d3
![image](https://github.com/aropan/clist/assets/8236389/45120387-f477-40ce-a334-f044c71c65a2)

Same issue on Sunday ( the next day )
https://clist.by/standings/weekly-contest-385-49725905/?list=a417ea34-3ddf-4fab-8802-8437626d23d3
![image](https://github.com/aropan/clist/assets/8236389/4fcf7362-b414-467e-84f2-24fb65f7c31c)

**Comment by manoharreddyporeddy** [comment]
May be, cadence of refresh can be:

. At 10th min
if no scores at this time
then at every 5 mins to check if there are scores

. +every 10 mins after 1st successful refresh

**Comment by aropan** [comment]
There is reparsing some other contests. It requires a lot of server memory and can't run parallel with main parsing process. I try to think about this next time.

Parsing standings of leetcode contest takes more than 10 minutes sometimes. If this doesn't happen then standings will be updated every 10 minutes.
