### ISSUE TITLE
Standings > Refresh interval is not fast enough

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#329]
Thanks for your work on clist, @aropan 

===

In the standings page
while contest is going on
it does not refresh enough times
The interval is not fast enough

There is delay of 30 minutes or so

======

Refresh can be at least be:
. Contest begin time
. Contest begin time + 10 mins - every 10 mins
. Contest begin time + 20 mins - every 10 mins

. Contest begin time + 40 mins - every 20 mins from here
. Contest begin time + 60 mins
. Contest begin time + 80 mins
. Contest begin time + 100 mins
. Contest begin time + 120 mins - contest ends here
. Contest begin time + 140 mins

. Contest begin time + 150 mins - 30 mins after contest

. Contest begin time + 180 mins - 1 hour after contest

======

Please check when possible.

https://leetcode.com/contest/weekly-contest-386/ranking/
https://clist.by/standings/weekly-contest-386-49882312/?list=a417ea34-3ddf-4fab-8802-8437626d23d3

![image](https://github.com/aropan/clist/assets/8236389/adbc523d-cea5-46e5-89d2-1ce0928cb5a8)

===

**Comment by manoharreddyporeddy** [comment]
Also, all are not included in standings

For example "razorsharp7" is missing today
https://clist.by/standings/biweekly-contest-125-49871532/?list=a417ea34-3ddf-4fab-8802-8437626d23d3

From below, it looks like refresh din't happen after 40 mins, those who attended at 1 hr time are not in list.
https://clist.by/standings/biweekly-contest-125-49871532/?languages=javascript&languages=typescript

![image](https://github.com/aropan/clist/assets/8236389/8657fd4c-852b-447b-aadc-788e4f42771e)

**Comment by aropan** [comment]
Fixed in #333. it won't be better than now.
