### ISSUE TITLE
Problems > Tags should be ordered

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#330]
Thanks for your work on clist, @aropan 

===

Tags should be ordered as in dictionary

For example
`greedy  array  hash table  counting`
	shud be
`array  counting  greedy  hash table`

===

https://clist.by/problems/?search=&resource=102&favorite=off&status=noallsolved&chart=&sort_order=asc&sort=rating

===

1
![image](https://github.com/aropan/clist/assets/8236389/34816d4a-099a-4eec-8ca4-8fbabadd91b0)

2
![image](https://github.com/aropan/clist/assets/8236389/c2e66544-fc39-49ce-a04f-2cb7a8ae2a70)

===

**Comment by aropan** [comment]
Why should tags be sorted?

It is better to keep the original order of tags - tags can be specified in order of importance for solving the problem.

**Comment by manoharreddyporeddy** [comment]
thanks @aropan for the reply

===

unclear on what is order of importance
but if its order of addition, it is fine, just when we add, for visual sake

however, 
on refresh of page, they shud be ordered
because
1 alphabetical is easy to read
2 either way it shows same results
3 found it very difficult when comparing results - may be i used Ctrl + F or similar when i raised this bug

**Comment by aropan** [comment]
`order of importance` means that earlier tag more relevant to problem.

**Comment by manoharreddyporeddy** [comment]
oh ok

for leetcode, i found that, order of importance is not really so good
that is, the 1st topic tag sometimes is not really relevant (or, very difficult to implement with 1st tag, also not easy to see )

may be, for other websites, order is more correct - then all good, we may close this issue in this case
