### ISSUE TITLE
Standings page > During contests, + button can be hidden

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#331]
Thanks for your work on clist, @aropan 

===

Minor issue
For better look and feel

In the Standings page
while contest is going on

The + button can be hidden
because the submission cannot be seen anyway
it just generates a timeout error

---

![image](https://github.com/aropan/clist/assets/8236389/5c9c1fbc-4929-4097-a83b-6b92780b62e0)

---

![image](https://github.com/aropan/clist/assets/8236389/b11bdbf3-ff28-48d4-a9db-e32f03b191a9)

---

https://clist.by/standings/weekly-contest-387-50023055/?list=a417ea34-3ddf-4fab-8802-8437626d23d3

![image](https://github.com/aropan/clist/assets/8236389/2bc59ce9-f4bf-4540-b241-4d90fb66a400)

---

**Comment by aropan** [comment]
Fixed.
