### ISSUE TITLE
Standings > Weekly Contest 388 - No standings

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#333]
thanks for your work on clist, @aropan 

====

i did most of the q2s
& touched 2000 question solutions
so i only use clist to see live standing during contest

last week, they not refreshed correctly ( if not 10 make 30 mins to avoid too many connection errors)
but today, they are missing totally

![image](https://github.com/aropan/clist/assets/8236389/ee831636-0032-4adc-9fbc-bf8d2a81706f)

**Comment by aropan** [comment]
😭

<img width="420" alt="image" src="https://github.com/aropan/clist/assets/1968460/6df82daa-5df4-4f4f-bfa8-457532240bba">

**Comment by manoharreddyporeddy** [comment]
Somehow it was working at some time 🤣
See https://lccn.lbao.site/predicted/weekly-contest-388

**Comment by manoharreddyporeddy** [comment]
Raised a ticket
https://leetcode.com/discuss/feedback/4854144/Leetcode-contest-api-is-not-working

**Comment by manoharreddyporeddy** [comment]
1 I have my own js api which is broken

2 But, in incognito it is working

So, may be, they changed api, we need to fix it ( esp some were able to do it https://github.com/aropan/clist/issues/333#issuecomment-1987191820 )

![image](https://github.com/aropan/clist/assets/8236389/ac3dd27a-3924-457f-b1a6-33e16c07e715)

**Comment by manoharreddyporeddy** [comment]
@aropan 

1 I tried several libraries, it dint work. 
2 However, after 30 mins of trails, below simple fix worked, hope you can use it and make clist backup for leetcode

we need to use `"User-Agent": "Mediapartners-Google"`

```
const httpsAgent = new https.Agent({ rejectUnauthorized: false });
res = await fetch(c_contest_api_url, {
  headers: {
    Referer: c_contest_url,
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "User-Agent": "Mediapartners-Google",  // <== This fixes fetch() fail with Cloudflare's 403 Just a moment...  issue
  },
  body: null,
  method: "GET",
  agent: httpsAgent,
});

res = await res.json();
```

Source - https://stackoverflow.com/a/67911765/984471

**Comment by aropan** [comment]
@manoharreddyporeddy 
This works locally on my laptop, but doesn't work on the server. 😔

**Comment by manoharreddyporeddy** [comment]
I think, when script runs on server, it is local to that server, so it should work
may be, something else is a problem, what is the error you have ?

**Comment by aropan** [comment]
It is very strange. Your headers work my laptop with `curl`. And it works on server. But doesn't work inside docker (CLIST) on server. I tried repeat query through `requests` and `wget` but they didn't work.

I have `curl 7.81.0` on server (works), have `curl 7.74.0` (doesn't work) inside docker. I compare communication log and see difference. Updated `curl 8.6.0` works.

I call `curl` from python with `subprocess` and parse output. 🤯

**Comment by aropan** [comment]
[Biweekly Contest 126](https://clist.by/standings/biweekly-contest-126-50167278/) parsed.

**Comment by manoharreddyporeddy** [comment]
for now, workaround is good

but today's contest is missing
https://leetcode.com/contest/weekly-contest-389/


![image](https://github.com/aropan/clist/assets/8236389/3ebcda45-1269-4a9b-ba82-af705c631e1c)

**Comment by SongHayoung** [comment]
can you update my profile too? Rating was missing past 3 weeks

https://clist.by/coder/songhayoung0_0/?search=resource:leetcode.com

**Comment by manoharreddyporeddy** [comment]
@aropan 

for now below is good, just add it as main script, so we can get today's contest https://leetcode.com/contest/weekly-contest-389/
> I call curl from python with subprocess and parse output. 

===

we can fix the actual issue later
maybe docker needs python, or other upgrade

**Comment by aropan** [comment]
@manoharreddyporeddy done.

Fixed all.

<img width="1368" alt="image" src="https://github.com/aropan/clist/assets/1968460/3555b6e7-1cc0-4a57-94c5-f40ac61b9e09">

**Comment by manoharreddyporeddy** [comment]
perfect 👍🤣❤️
thanks
