### ISSUE TITLE
Contests number of Most participated is incorrect for leetcode

### ISSUE THREAD

**Issue by jcaosola** [aropan/clist#334]
leetcode official profile shows correct Attended number (=430) while clist profile does not.
![image](https://github.com/aropan/clist/assets/7110993/10abbcf3-284a-420c-afb5-fb8f9b7a6e84)

It appears that my previous username hasn't been accounted for. while rating did change.
![image](https://github.com/aropan/clist/assets/7110993/be86e770-9030-47d4-8690-9f9f64afdbd4)

**Comment by aropan** [comment]
@jcaosola is `jcaoso1a` your previous account? Or any others? This could help with recovery your history. 

I deleted accounts that got 404 on profile page (as example https://leetcode.com/jcaoso1a/). I think these accounts removed (banned or deactivated). Now I don't do it - I mark account as deleted and can renamed it later.

**Comment by jcaosola** [comment]
yes, it's my previous username for the same account

**Comment by aropan** [comment]
[ceass20xx](https://clist.by/coder/ceass20xx/)

Fixed.
