### ISSUE TITLE
The events homepage has a lot of events and feels cluttered.

### ISSUE THREAD

**Issue by 21Cash** [aropan/clist#337]
![garb](https://github.com/aropan/clist/assets/113699753/41ec0447-f095-4ebe-b131-64f1569441e2)

Can you add like a set of resources options (say LC, CF, AtCoder) we can choose so that only the events from the chosen ones appear on the homepage.

**Comment by aropan** [comment]
You could be use [filters](https://clist.by/settings/filters/). Looks like:
<img width="840" alt="image" src="https://github.com/aropan/clist/assets/1968460/3b871df6-7f5f-4e49-b5cb-27337b45026b">

**Comment by aropan** [comment]
Or using `q` get param for filtering by regex: https://clist.by/?q=leetcode.com%7Ccodeforces.com%7Catcoder.jp&view=list

Result:
<img width="1545" alt="image" src="https://github.com/aropan/clist/assets/1968460/cab41931-2a51-4cde-a42f-1fbb6ec28c9e">
