### ISSUE TITLE
Add basecamp.eolymp.com

### ISSUE THREAD

**Issue by mstrechen** [aropan/clist#338]
Hi! 
I couldn't find docs on how to add a new contest source and I couldn't figure it out by myself (specifically how to run legacy parsers locally). 
So I would much appreciate any links/examples on that matter, or if you could add [basecamp.eolymp.com](https://basecamp.eolymp.com/en/contests) to the list of sources. The platform has GraphQL API ([explore](https://api.eolymp.com/spaces/00000000-0000-0000-0000-000000000000/explore)), so it shouldn't be that hard. 

Thanks in advance!

**Comment by aropan** [comment]
@mstrechen 
Hi. Could I get standings and problems through this API? Now I got:

```
{
  "errors": [
    {
      "message": "rpc error: code = Unauthenticated desc = unauthenticated",
      "path": [
        "contests",
        "nodes",
        0,
        "participants"
      ],
      "extensions": {
        "code": "UNAUTHENTICATED"
      }
    },
    {
      "message": "rpc error: code = Unauthenticated desc = unauthenticated",
      "path": [
        "contests",
        "nodes",
        0,
        "problems"
      ],
      "extensions": {
        "code": "UNAUTHENTICATED"
      }
    }
  ],
  "data": {
    "contests": {
      "nodes": [
        {
          "id": "n4rbvsi2lt50t4b1h0ccl1oi3c",
          "name": "Weekend Practice #1",
          "participants": null,
          "problems": null
        }
      ]
    }
  }
}
```

**Comment by aropan** [comment]
I think this will be useful. And there was access to standings and problems on eolymp.com.

**Comment by aropan** [comment]
@mstrechen 
[basecamp.eolymp.com](https://basecamp.eolymp.com/en/contests) duplicates contests from [eolymp.com](https://www.eolymp.com/en/contests)? Or eolymp have same contests as basecamp.eolymp.com? If it is true then I don't see why add duplicate resource.

**Comment by mstrechen** [comment]
@aropan right now the contests are hosted on basecamp.eolymp.com (if you click on any of the contests on eolymp.com you would be redirected). Besides that, eolymp.com itself is going to be sunset soon. 

Sure, no need to duplicate things. I actually created this issue since I noticed that the "Eolymp Weekend Practice #1" contest didn't appear on clist.by. 

There will be Eolymp Weekend Practice #2 soon, I could let you know once it appears in the list. And thanks for the help!

**Comment by aropan** [comment]
Yeah, I fixed missing contests. New ones will appear automatically.

**Comment by skolodyazhnyy** [comment]
@aropan you might consider using [API](https://support.eolymp.com/en/dev/api) to [get a list of upcoming contests](https://support.eolymp.com/en/dev/reference/services/eolymp.judge.ContestService).

The API reference is available [here](https://support.eolymp.com/en/dev/reference) as well as there is [GraphQL explorer](https://api.eolymp.com/spaces/00000000-0000-0000-0000-000000000000/explore). 

I'm sorry the documentation is very raw and incomplete, but if you need some help I can answer questions and provide whatever assistance is required.
