### ISSUE TITLE
Standings > Weekly Contest 390 - Some ratings are not updated

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#339]
Thanks for your work on clist, @aropan 

===

Some ratings are not updated, see below link & SS:

https://clist.by/standings/weekly-contest-390-50494892/?list=a417ea34-3ddf-4fab-8802-8437626d23d3

![image](https://github.com/aropan/clist/assets/8236389/753f96d5-badb-456d-ad8d-2318ac0fcd33)

**Comment by aropan** [comment]
This requires a little more time.
