### ISSUE TITLE
Problems > Few issues

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#340]
Thanks for your work on clist @aropan 

===

i opened all below from clist
using link like below
https://clist.by/problems/?search=&resource=102&favorite=off&status=noallsolved&chart=&sort_order=asc&sort=rating

looks like, below 4 problems have issues in link, etc

===

1
https://leetcode.com/problems/bulb-switcher-iv/
link is broken

2
https://leetcode.com/problems/non-decreasing-subsequences/
submitted 15 mins ago
after update button is pressed
but it does not turn to green

3
https://leetcode.com/problems/minimum-time-to-make-rope-colorful/
i opened this link from clist
but i cannot find the problem

4
currently "key" looks like problem number, but it is not
i verified, but dint find any other field which are not problem number

![image](https://github.com/aropan/clist/assets/8236389/9764c664-0174-4686-9b77-bf990f16da27)

![image](https://github.com/aropan/clist/assets/8236389/334bca3c-1992-434f-bd6a-c11ccaae88fa)

===

**Comment by aropan** [comment]
2. It doesn't reproduce now.
3. [Fixed](https://clist.by/problems/?search=Minimum+Time+to+Make+Rope+Colorful).
