### ISSUE TITLE
Standings - Leetcode contests are not updating - Biweekly Contest 127, Weekly Contest 391

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#342]
Thanks for your work on clist, @aropan 

===

Looks like
Yesterday & today Leetcode contests are not updating

I touched 2000 problems solved and I am not doing any problems actively
So I look forward this Live contests in a week the most 🤣 hope they will be up soon

===
https://clist.by/standings/biweekly-contest-127-50494891/?list=a417ea34-3ddf-4fab-8802-8437626d23d3

![image](https://github.com/aropan/clist/assets/8236389/30ededa1-8a58-4ba3-a0df-b32f09289b75)

https://clist.by/standings/weekly-contest-391-50647343/?list=a417ea34-3ddf-4fab-8802-8437626d23d3

![image](https://github.com/aropan/clist/assets/8236389/0732afca-3657-4c94-96c3-6a434fdbded7)

**Comment by aropan** [comment]
This was my failure. Fixed.

P.S. Sometimes leetcode blocks more queries than usual. I hope it is temporary issue.
