### ISSUE TITLE
Standings > Weekly-contest-199 - Language filter is missing

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#346]
Thanks for the work on clist @aropan 

===

Language filter is missing for some contests

If possible, please check for others also.

===

Example:

Missing for Weekly-contest-199

https://clist.by/standings/weekly-contest-199-20877320/
![image](https://github.com/aropan/clist/assets/8236389/02280890-b5ab-4956-9bc0-120c3aecb186)

Present for Weekly-contest-200

https://clist.by/standings/weekly-contest-200-20987715/
![image](https://github.com/aropan/clist/assets/8236389/208c90ea-624b-4902-91c8-80f16d0e9950)

**Comment by aropan** [comment]
Fixed.
