### ISSUE TITLE
Feature request: Use intervals instead of sliders in problem difficulty filtering

### ISSUE THREAD

**Issue by michelececcacci** [aropan/clist#347]
Right now if i want to select problem ranges i have to use these sliders:
![image](https://github.com/aropan/clist/assets/75946413/38626392-fde3-416c-9cb2-40d9b52cdf56)
I would much rather use something like what codeforces  does: 
![image](https://github.com/aropan/clist/assets/75946413/4de787c4-5aed-44cd-adff-7eed16ff403c)
The main reasoning behind this change is that it allows for more precise rating boundaries.
I'd be willing to do this myself. I tried looking for similar issues, but i couldn't find any.

**Comment by aropan** [comment]
It's already working. 🙂

https://github.com/aropan/clist/assets/1968460/d9029c8d-4495-4db4-9567-9f3c5a934b14

**Comment by michelececcacci** [comment]
I didn't realize you could do that. That's amazing
