### ISSUE TITLE
Standings > live updates - few issues

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#348]
Thanks for the work on clist, @aropan 

===

This week, its better, in below URL, the live scores are coming fine partially
https://clist.by/standings/weekly-contest-393-50980850/?list=a417ea34-3ddf-4fab-8802-8437626d23d3

===

This week issues observed are below:

===

1 In below screenshot, it shows 35 mins ago updated
the contest is done 5 mins ago
which means for last 30 mins there was no update

![image](https://github.com/aropan/clist/assets/8236389/d6497e20-663c-4728-a88e-a9a12935deb3)

===

2 Also, some users are missing in the ranks
there large difference between rank, for number 10 & 11

1764 (10)
8594 (11)

![image](https://github.com/aropan/clist/assets/8236389/46b28c1a-4d8c-46f8-a518-ce18eb9b95d7)

===

**Comment by aropan** [comment]
The update was just slow. I made some minor edits - run updating accounts not during the contest.
