### ISSUE TITLE
About highlight displays of problem up-solving

### ISSUE THREAD

**Issue by Kevin114514** [aropan/clist#350]
Currently, a tried-after-contest problem will be marked highlighted in green regardless of whether it's currently AC of not. Maybe you can highlight the up-solved problems and the tried problems in different colors.

**Comment by aropan** [comment]
@Kevin114514 can you give more information (coder, profile, resource, problem)?

**Comment by Kevin114514** [comment]
my clist profile name is Kevin, my cf account is Kevin114514, and the regarding problem is cf1383f

**Comment by Kevin114514** [comment]
![Uploading issue.png…]()

**Comment by aropan** [comment]
Fixed. Thank you for your feedback. Your coder has been corrected. The rest will be fixed within the day.
