### ISSUE TITLE
Missing statistics if solved 0 problems in contests

### ISSUE THREAD

**Issue by chinesedfan** [aropan/clist#352]
I performed very badly in CodeChef Starters 129 Division 1 (handle: chinesedfan), with several failed attempts and 0 problems solved. The official standing didn't contain my name, so it was fine for me that no statistics in my profile (https://clist.by/coder/chinesedfan/).

But after upsolved, is it possible to show?

P.S. I tried to read and understand this project's logic, and found crontab in /legacy/update.bash. Still don't know how it invokes /legacy/module to update database. Can you give some hits?

**Comment by chinesedfan** [comment]
Updated: I started the docker container and saw the Django website, but the database was empty. Especially, how to init table clist_resource? Did you add manually? Maybe a new developer still needs some steps to run legacy container and prepare google calender auth.

**Comment by aropan** [comment]
> P.S. I tried to read and understand this project's logic, and found crontab in /legacy/update.bash. Still don't know how it invokes /legacy/module to update database. Can you give some hits?

Legacy code is used only for schedule updates. Update standings and account info are done via [parse_statistic](https://github.com/aropan/clist/blob/master/src/ranking/management/commands/parse_statistic.py) and [parse_accounts_infos](https://github.com/aropan/clist/blob/master/src/ranking/management/commands/parse_accounts_infos.py) respectively. They both use [codechef.py](https://github.com/aropan/clist/blob/master/src/ranking/management/modules/codechef.py) module.

**Comment by aropan** [comment]
> Especially, how to init table clist_resource? 

I haven't done this yet. I'll think about how to do this automatically.

**Comment by aropan** [comment]
> But after upsolved, is it possible to show?

Yes, after upsolved and reupdate your codechef account. I also think add it automatically also (without needs upsolving).

**Comment by aropan** [comment]
Fixed. All codechef accounts will are fixed automatically after account updating.

**Comment by chinesedfan** [comment]
Thanks. Now I can see the contest in [my list](https://clist.by/account/chinesedfan/resource/codechef.com/), but no events belong to it, can upsolved problems be shown there?

**Comment by aropan** [comment]
Fixed.
