### ISSUE TITLE
Hackerearth rating change hasn't reflected

### ISSUE THREAD

**Issue by RedHeadphone** [aropan/clist#353]
HackerEarth profile: https://www.hackerearth.com/@redheadphone
Clist profile: https://clist.by/account/redheadphone/resource/hackerearth.com/

On HackerEarth it shows that my contest rating is 1920, but on Clist, it hasn't updated my last contest rating delta.

**Comment by aropan** [comment]
<img width="1524" alt="image" src="https://github.com/aropan/clist/assets/1968460/f18a4ab1-d9b2-4a3d-8f04-2479844c3f94">

And I'm waiting response from HackerEarth support team.
