### ISSUE TITLE
Biweekly Contest 129 > Standings

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#355]
Thanks for the work on clist @aropan 

========

Its been 8 hours but no standings still.
may be, we should retry if failure, every 1 hour, if there are No standings

https://clist.by/standings/biweekly-contest-129-51121218/?list=a417ea34-3ddf-4fab-8802-8437626d23d3

![image](https://github.com/aropan/clist/assets/8236389/194bee17-9359-43c6-9269-24aa8d3de0d4)

**Comment by manoharreddyporeddy** [comment]
Same issue in today's Weekly contest

![image](https://github.com/aropan/clist/assets/8236389/f9f630e4-ec3c-4846-87c1-555b46f6d40c)

https://clist.by/standings/weekly-contest-395-51274175/?list=a417ea34-3ddf-4fab-8802-8437626d23d3

**Comment by aropan** [comment]
Wow, 395 was parsed (without any fixes):

<img width="1118" alt="image" src="https://github.com/aropan/clist/assets/1968460/4dd2f146-cdb0-4156-8861-a00d3d4ebe7b">

**Comment by aropan** [comment]
Fixed. I added more common headers (not only https://github.com/aropan/clist/issues/333#issuecomment-2001993072) and it works better.

**Comment by manoharreddyporeddy** [comment]
Works perfectly now ❤️
https://clist.by/standings/biweekly-contest-129-51121218/?list=a417ea34-3ddf-4fab-8802-8437626d23d3
https://clist.by/standings/weekly-contest-395-51274175/?list=a417ea34-3ddf-4fab-8802-8437626d23d3
![image](https://github.com/aropan/clist/assets/8236389/518a4c70-d773-4ca0-961e-4069c58e46e9)

Wish this will be automatic parse
& can watch a live match next time 🤣👍

**Comment by aropan** [comment]
> can watch a live match next time

🤞🏻
