### ISSUE TITLE
Standings > + click for answer > 504 Gateway Time-out

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#358]
Thanks for your work on clist, @aropan 

===

1 Clicking on + icon to view answer at 
https://clist.by/standings/weekly-contest-396-51417724/?list=a417ea34-3ddf-4fab-8802-8437626d23d3
is giving this error `504 Gateway Time-out`

![image](https://github.com/aropan/clist/assets/8236389/37044820-4663-4ef8-a912-fcf6589e7d95)

2 `You can check here` link takes to below, which also errors in `504 Gateway Time-out`
https://clist.by/solutions/63582015/Q1/

![image](https://github.com/aropan/clist/assets/8236389/55acd813-4ca4-4fc2-a584-fd188abcbd97)

**Comment by manoharreddyporeddy** [comment]
I saw this error last week too

**Comment by aropan** [comment]
There is no problem now.
