### ISSUE TITLE
Coder/ Account > In progress as %

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#359]
Thanks for the work on clist, @aropan 

===

Coder/ Account > In progress as %

Currently the spinner spins - sometimes for little time or sometimes for a very long time

If there is a % given - like 10% done, it will help
Or, a progress bar will help.

===

![image](https://github.com/aropan/clist/assets/8236389/8b1047d6-ea80-4dc8-b213-f355d66c4f21)

===

**Comment by aropan** [comment]
Percentage is difficult to calculate. I added number of accounts that remain to be updated.


https://github.com/aropan/clist/assets/1968460/cd8e20b9-75d5-4c9a-8d13-14649f67460c

**Comment by manoharreddyporeddy** [comment]
I thought
the ticket request was for updating 1 account
so may be 15 questions, and recent contest details of this one account will be updated for this 1 account.

Just checking
what is "2670 accounts" shown in video

This will help others understand how clist works when Update button is clicked, and not raise this % question again.

**Comment by aropan** [comment]
"N accounts to update" is number of accounts that are still planned to be updated. When this value drops to 0, your account will definitely be updated.
