### ISSUE TITLE
clist does not merger the old and the new domain contest  records

### ISSUE THREAD

**Issue by sunyafei123** [aropan/clist#362]
When I changed leetcode-cn domain, clist didn't display the merged contest records but the new domain contest records. for example,[the old domain](https://clist.by/account/trusting-paninikta@.cn/resource/leetcode.com/) ,[the new domain](https://clist.by/account/sunyafei@.cn/resource/leetcode.com/)

**Comment by aropan** [comment]
Thanks. Fixed.
