### ISSUE TITLE
Standings > Biweekly Contest 131 is not live

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#365]
Thanks for the work on clist @aropan 

===

Standings > Biweekly Contest 131 is not live today.
It is almost 1hour 15 mins passed since contest began

https://clist.by/standings/biweekly-contest-131-51676012/

![image](https://github.com/aropan/clist/assets/8236389/d4062681-2d94-4668-99bb-951a793faedb)

**Comment by aropan** [comment]
Fixed.
