### ISSUE TITLE
Standings > Solutions > Plus button is not showing solution on 1st time

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#372]
thanks for the work on clist @aropan 

====

Clicking on + button is
1 taking to another window, always, 1st time click
2 with none in dialog

https://clist.by/standings/weekly-contest-400-51941985/?list=a417ea34-3ddf-4fab-8802-8437626d23d3

===

![image](https://github.com/aropan/clist/assets/8236389/635f3547-2039-4cd7-a614-6219eab931c6)

====

![image](https://github.com/aropan/clist/assets/8236389/34ec124d-8c35-43d0-aea9-1e2828e92731)

**Comment by aropan** [comment]
Improved behavior a little. But it won't help to view solution if proxy isn't found.
