### ISSUE TITLE
An api that returns problem list for a given Contest ID

### ISSUE THREAD

**Issue by sharoha** [aropan/clist#374]
Hi,

I am currently working on a use case that requires fetching all problems for a given contest. For instance for a contest with ID "weekly-contest-400", I am expecting the following templated response.

```json
{ 
     "contestId": "weekly-contest-400",
     "problemList": [
             "problemDescription": "$problem_description", 
             "test_cases": [
               // all test cases for this problem
             ]
     ]
}
```
Wanted to check if the  current repo supports a query like above?

**Comment by chinesedfan** [comment]
Yes, use /contest api according to https://clist.by/api/v4/doc/.

And you can also check my examples,
- https://github.com/chinesedfan/clist-ex/blob/master/src/apis/index.ts#L77
- https://github.com/chinesedfan/clist-ex/blob/master/src/pages/ProblemList.tsx#L76

**Comment by aropan** [comment]
Sorry, this data isn’t available and won’t be added soon.
