### ISSUE TITLE
Standings > Biweekly Contest 132 > Q2 % looks incorrect

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#377]
Thanks for your work on clist, @aropan 

===

1,5% does not look correct for Q2

![image](https://github.com/aropan/clist/assets/8236389/a3355a11-66cf-412a-ae1a-7d09a4108eaa)

**Comment by aropan** [comment]
This is the fill percentage. What is wrong?

**Comment by aropan** [comment]
This is the fill percentage. What is wrong?

**Comment by manoharreddyporeddy** [comment]
I thought it is pass %
what is fill percentage ? May be add a tooltop/help somewhere.

It is very large for all other questions

===

![image](https://github.com/aropan/clist/assets/8236389/da237a7e-8152-4cf8-8239-0da28d567afa)


![image](https://github.com/aropan/clist/assets/8236389/293f17e1-06b5-469a-bb78-8f50dc2909f4)

![image](https://github.com/aropan/clist/assets/8236389/4eb75c55-da5b-45d4-ac79-2b04fa8dce4d)

**Comment by aropan** [comment]
> What is fill percentage ?

Fill percentage of next rating level.

> May be add a tooltop/help somewhere.

I think this is not necessary.

**Comment by manoharreddyporeddy** [comment]
Fill percentage of next rating level
What it means is not clear at all - for me :)
But its ok, may be others will understand
