### ISSUE TITLE
Standings > Weekly Contest 401 - Data is lost

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#378]
Thanks for your work on clist, @aropan 

===

I think some data is lost
many users attended contest, but it does not show green (attended contest ) but blue ( up solving)
This is same since few days back. If it is possible, please revert to previous version of code & DB.

===

https://clist.by/standings/weekly-contest-401-52071232/?list=a417ea34-3ddf-4fab-8802-8437626d23d3

![image](https://github.com/aropan/clist/assets/8236389/21bdb6e4-e6c1-4282-97e6-26a4c8009213)

**Comment by aropan** [comment]
Duplicate #370.
