### ISSUE TITLE
Standings > Weekly Contest 402 - outdated

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#379]
thanks for the work on clist, @aropan 

===

the Standings of Weekly Contest 402 are not up to date

Its about 40 mins
past contest end time
but the ratings are not up to date

here it is up to date - https://lccn.lbao.site/predicted/weekly-contest-402

one way to fix this issue is
fetching can be done in 2 passes
- 1st pass get only ratings
- 2nd pass get answers

when 1st pass is done, we can see below correctly
      Score | Penalty | PredictedNewRating | PredictedRatingPerf
when 2nd pass is done, we can see below correcly
      Q1 | Q2 | Q3 | Q4
    also + mark to see code will be enabled

by this way
use to 2 passes
the ratings will come sooner
and  we can see ratings correctly similar to https://lccn.lbao.site/predicted/weekly-contest-402  without any delay

===

![image](https://github.com/aropan/clist/assets/8236389/87817a78-0084-4720-b681-2a42be57def2)

**Comment by manoharreddyporeddy** [comment]
Thanks @aropan 
It been a few days, can you update this contest data temporarily for now.

**Comment by aropan** [comment]
Duplicate #370.
