### ISSUE TITLE
Standings - Biweekly Contest 133 - Not synced yet

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#381]
Thanks for your work on clist, @aropan 

===

Could you please update the ratings, for Biweekly Contest 133?

https://clist.by/standings/biweekly-contest-133-52180329/
![image](https://github.com/aropan/clist/assets/8236389/396cb701-5a90-4d14-8803-8bff51ed92dd)

**Comment by aropan** [comment]
Duplicate #370.
