### ISSUE TITLE
Add a site-out message

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#382]
Thanks for your work on clist, @aropan 

====

It's been a week or so, since the contests are not updating.
Please add a site out message.
Message can be specific to contest, etc.

![image](https://github.com/aropan/clist/assets/8236389/1c476124-8941-4f6d-8d35-89b703c60584)

====

![image](https://github.com/aropan/clist/assets/8236389/067e0419-0fed-4f27-896b-9a206b905c3f)

**Comment by aropan** [comment]
Relates to #421
