### ISSUE TITLE
Support questionFrontendId for leetcode.com

### ISSUE THREAD

**Issue by chinesedfan** [aropan/clist#384]
Now clist invokes https://leetcode.com/contest/api/info/{contestSlug}/ to get `question_id`, which is different with the id that we see in browsers. 

For example, "1791. Find Center of Star Graph", `question_id` is 1916, but `questionFrontendId` is 1791.

FYI, I find it can be queried by GraphQL. Not sure whether it can be implemented by clist. You can also [search in Github](https://github.com/search?q=questionFrontendId+language%3AJavaScript&type=code&l=JavaScript) and find more examples.

```
// https://leetcode.com/graphql/, the request payload is,
{"query":"\n    query questionTitle($titleSlug: String!) {\n  question(titleSlug: $titleSlug) {\n    questionId\n    questionFrontendId\n    title\n    titleSlug\n    isPaidOnly\n    difficulty\n    likes\n    dislikes\n    categoryTitle\n  }\n}\n    ","variables":{"titleSlug":"find-center-of-star-graph"},"operationName":"questionTitle"}
```

**Comment by aropan** [comment]
<img width="1409" alt="image" src="https://github.com/user-attachments/assets/1f23e134-af31-41c6-8ef5-13116e892070">
Added `id` field by default for leetcode.com resource.

**Comment by chinesedfan** [comment]
@aropan Did you refresh all leetcode's problems, or just recent contests?
