### ISSUE TITLE
Add nowcoder.com

### ISSUE THREAD

**Issue by chinesedfan** [aropan/clist#385]
Nowcoder is another famous website in China, as well as leetcode.com. It has more than 9M users and served 2k+ companies. See details in [about](https://www.nowcoder.com/nowcoder/about).

Website link: https://ac.nowcoder.com/
Contests page and api: 
- https://ac.nowcoder.com/acm/contest/calendar
- https://ac.nowcoder.com/acm/calendar/contest?token=&month=2024-6&_=1719587392225

I really want to contribute to this project, especially for adding websites in Chinese. But due to #354, I can still ask for your help this time. You may face the same problem when registering without a mobile number in China (#259). Good luck!

**Comment by chinesedfan** [comment]
Done. Great enhancement!

**Comment by aropan** [comment]
Added problem rating https://clist.by/problems/?resource=166&chart=rating.
