### ISSUE TITLE
UI Issue: Start/End Time doesn't add up in logic.

### ISSUE THREAD

**Issue by kripa-sindhu-007** [aropan/clist#387]
Start/End Time often confuses as there is a separate column for the contest's duration. Start Time should be enough to mention.

![image](https://github.com/aropan/clist/assets/152695457/60f41010-dcf7-40bc-8b9c-78a49af4582d)

**Comment by kripa-sindhu-007** [comment]
@aropan I would like to work on this issue. Please assign this to me.

**Comment by aropan** [comment]
Thank for you point but I don't agree with that mentioning the start time is enough. If an event is long, I want to know the end time so I can plan to attend.

**Comment by kripa-sindhu-007** [comment]
Agreed this can be one way to think.😊

**Comment by aropan** [comment]
Minor changes:

<img width="1572" alt="image" src="https://github.com/user-attachments/assets/839f1f8e-a0ba-478a-a864-0ccfa8ede524">

**Comment by kripa-sindhu-007** [comment]
Yeah!! This seems more logical.
![NoiceNiceGIF](https://github.com/user-attachments/assets/a489159a-307f-481b-ae86-47f69bd027aa)
