### ISSUE TITLE
Some of the Contest Data is Missing

### ISSUE THREAD

**Issue by Physics212303** [aropan/clist#389]
https://clist.by/standings/atcoder-beginner-contest-254-35239812/
There is a "delta", but there's no contest result.

**Comment by aropan** [comment]
Could you clarify what you mean?

**Comment by Physics212303** [comment]
I'm sorry that I gave the wrong link before. You can check it [here](https://clist.by/standings/atcoder-beginner-contest-259-35703549/?find_me=48159822), I lost my data in this contest.
And these contests have the same situation:
[ABC250](https://clist.by/standings/atcoder-beginner-contest-250-34486935/?find_me=48159774) [ABC251](https://clist.by/standings/panasonic-programming-contest-2022atcoder-beginner-contest-251-34790583/?find_me=48159792) [ABC252](https://clist.by/standings/atcoder-beginner-contest-252-34791742/?find_me=48159799) and so on.

**Comment by aropan** [comment]
Fixed.
