### ISSUE TITLE
Standings > Since last 2 contests are not official the contest data is incorrect

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#394]
Thanks for your work on clist, @aropan 

===

Since last 2 contests are not official
the contest data is incorrect

https://clist.by/standings/weekly-contest-407-52805839/?list=a417ea34-3ddf-4fab-8802-8437626d23d3
![image](https://github.com/user-attachments/assets/40958a67-6895-4a20-93fc-8ff4d23e7c39)

**Comment by aropan** [comment]
Where I can read about this?

**Comment by aropan** [comment]
Ok, I found - [Weekly Contest 405](https://leetcode.com/discuss/general-discussion/5431651/weekly-contest-405#:~:text=After%20careful%20consideration%2C%20we%20decided%20to%20unrate%20the%20contest) and [Weekly Contest 406](https://leetcode.com/discuss/general-discussion/5473054/weekly-contest-406#:~:text=To%20maintain%20the%20integrity%20of%20the%20competition%2C%20we%20have%20decided%20to%20unrate%20this%20contest).

**Comment by aropan** [comment]
Fixed.
