### ISSUE TITLE
Standings > Code link > More specific error is better

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#395]
Thanks for the work on clist , @aropan 

===

More specific error is better than below
is it error on clist, or leetcode, or a bit more specific is better

if it works, it works
but when it does not work, then whole day we cannot see code samples

===

https://clist.by/standings/weekly-contest-407-52805839/?list=a417ea34-3ddf-4fab-8802-8437626d23d3

![image](https://github.com/user-attachments/assets/d17cd31d-5949-4b55-aa55-fe58b67c1138)

**Comment by aropan** [comment]
Fixed.

I've been see it before. Cause is new data_region `LY` (I don't know what is): 
<img width="305" alt="image" src="https://github.com/user-attachments/assets/03b9b732-b0dc-4668-be43-a9cbfd47dc4e">
