### ISSUE TITLE
Problems page > Filter non-premium Vs premium only question list

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#400]
Thanks for your work on clist, @aropan 

===

Thanks for adding all questions including non-contest questions ❤️👍

===

JFYI below
Previously, I have marked all premium as Stars, however as of today it seems all those Star saves are lost.
i am applying Stars for premium again, this is not a issue for now.

===

Question
1
Is it possible to filter premium only?
2
Is it possible to filter non-premium only?
3
Search filter tooltip is not clear, on how to filter on fields.
The &&premium:1, premium:true, premium:yes, premium:on does not work in filter for this field.

SS below.

===

I use this for algorithms

https://clist.by/problems/?search=%21tag%3Adatabase+%26%26+%21tag%3Apandas+%26%26+%21tag%3Ajavascript+%26%26+%21tag%3Aconcurrency&resource=102&field=premium&field=difficulty&field=accepted_rate&rating_from=0&rating_to=5000&favorite=on&favorite=off&status=noallsolved&sort_order=desc&sort=accepted_rate

===
Premiums
![image](https://github.com/user-attachments/assets/25dcb510-d634-44cc-b50c-00f7cde36b73)

Filter tool tip
![image](https://github.com/user-attachments/assets/f9137edd-b90b-45ba-8e1b-16bc246f4650)

===

**Comment by aropan** [comment]
Done.

Add `premium` column. Choose value of `premium` in additional select. Or use [premium=false](https://clist.by/problems/?resource=102&premium=false) query param.

https://github.com/user-attachments/assets/89dc1d87-481c-4af7-8abe-0240a919317e

**Comment by manoharreddyporeddy** [comment]
clist is more useable now ❤️
