### ISSUE TITLE
Standings page > Some New Ratings are not updated

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#401]
Thanks for your work on clist, @aropan 

===

At https://clist.by/standings/biweekly-contest-137-53190503/?list=a417ea34-3ddf-4fab-8802-8437626d23d3
Some new ratings are not updated
SS below

Even the Update button is not updating them
- https://clist.by/coder/pgmreddy/
- https://clist.by/account/pgmreddy@.com/resource/leetcode.com/

===

![image](https://github.com/user-attachments/assets/9a3d2a02-1f07-4482-a1ad-442dbfd1539b)

**Comment by aropan** [comment]
What you mean when say "Update button"?

**Comment by aropan** [comment]
If I look correctly, then rating was updated between  Aug. 21, 2024, 4:10 a.m. and Aug. 21, 2024, 5:58 p.m. So it is long time after end of [Biweekly Contest 137](https://leetcode.com/contest/biweekly-contest-137/ranking).

**Comment by manoharreddyporeddy** [comment]
> What you mean when say "Update button"?

like
can anyone
trigger the update ranking
that will take from leetcode and update in clist?

current Update button on account
does many many records
i thought it can update ranking too - when some ranking are not filled

**Comment by manoharreddyporeddy** [comment]
> If I look correctly, then rating was updated between Aug. 21, 2024, 4:10 a.m. and Aug. 21, 2024, 5:58 p.m. So it is long time after end of [Biweekly Contest 137](https://leetcode.com/contest/biweekly-contest-137/ranking).

hmm

some were updated
some were not updated

**Comment by aropan** [comment]
I increased number of days that leetcode will be updated from 4 days to 6.
