### ISSUE TITLE
Standings > Biweekly Contest 137 > Some users are missing

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#402]
Thanks for your work on clist, @aropan 

===

Some users at 13K+ are missing, in Biweekly Contest 137

---

Biweekly ( missing )
https://clist.by/standings/biweekly-contest-137-53190503/?search=kirk_s
![image](https://github.com/user-attachments/assets/2e2a478f-851e-4f41-b880-b1292c54adb1)

---

Weekly
https://clist.by/standings/weekly-contest-411-53327265/?search=kirk_s
![image](https://github.com/user-attachments/assets/45dd1b9f-413b-42a4-bb01-062454b1ce43)

---

Biweekly - Other website
https://lccn.lbao.site/predicted/biweekly-contest-137
![image](https://github.com/user-attachments/assets/acc16cb5-6209-4065-93f4-2488f6f0d898)

---

**Comment by aropan** [comment]
All participants who do not have any accepted task are ignored. Because it is impossible to understand these participants submit something or not. After account updating who have rating change will be added to standings. As example [kirk_s](https://clist.by/standings/biweekly-contest-137-53190503/?search=kirk_s).

**Comment by manoharreddyporeddy** [comment]
No tasks accepted, ignored, makes sense 👍
Thanks for fixing for given user ❤️. Hope it will update itself next time 😊

**Comment by manoharreddyporeddy** [comment]
[Update]
I rechecked the given user, after my above comment, so updated it.
User's 1st question was accepted earlier, it was shown on clist
However it is changed as WA now on Leetcode as of today, due to new test cases added.
So all good, ty
