### ISSUE TITLE
Standings > Add external link

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#403]
Thanks for your work on clist, @aropan 

===

In Standings page, add direct external link to https://leetcode.com/u/uwi/ for example
This way, going via Account/Coder to click direct link is not required, one less server call.

https://clist.by/standings/weekly-contest-412-53455428/?list=a417ea34-3ddf-4fab-8802-8437626d23d3

===

![image](https://github.com/user-attachments/assets/5d4cbc6e-260e-4b3b-8c1e-f5095270d8c5)

**Comment by aropan** [comment]
Oh, I wanted more clicks on the site. 😊

Added.

<img width="350" alt="image" src="https://github.com/user-attachments/assets/4a2b5f50-ad69-4614-bc92-15dc4e0cc26c">
<img width="695" alt="image" src="https://github.com/user-attachments/assets/453b117f-1bd7-400f-9fea-e457e57f55ba">

**Comment by manoharreddyporeddy** [comment]
> Oh, I wanted more clicks on the site. 😊

You will & you should. Add even more features. 🤣
