### ISSUE TITLE
Standings > Update all accounts in list, when it is applied, so Predicted New Rating will be correct

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#404]
Thanks for your work on clist, @aropan 

===

When a list is applied like below:
https://clist.by/standings/weekly-contest-412-53455428/?list=a417ea34-3ddf-4fab-8802-8437626d23d3

All users in that list, must get updated.

Below message should not show for users in that list
![image](https://github.com/user-attachments/assets/f4307866-7d9c-4723-946f-aa17ccd4f707)

Otherwise the "Predicted New Rating" calculation is not correct because previous rating is not correct.
![image](https://github.com/user-attachments/assets/9ebe52cb-45c9-41e3-ae89-19abb89b855e)

**Comment by aropan** [comment]
Predicted rating won't exactly correct while all accounts doesn't update (not only for specific account).

I don't have plan using information of coder lists to update accounts. And I will implement fast updating only rating of all accounts.

**Comment by manoharreddyporeddy** [comment]
For some of the top 10 in below link

only a few have coder accounts
others just have have accounts

but their rating is correct

the same could be done
 for all the  list people
 somehow, i felt 

https://clist.by/standings/weekly-contest-412-53455428/?list=a417ea34-3ddf-4fab-8802-8437626d23d3

@aropan
