### ISSUE TITLE
Activate Rating and Resource Rank for "geeksforgeeks.org" in Accounts Webpage

### ISSUE THREAD

**Issue by Gowtham-the-explorer** [aropan/clist#406]
Thanks for your work on clist, @aropan 

> **Rating** and **Resource Rank** @geeksforgeeks

Till now, the aforementioned attributes haven't been deployed in a working state.
You can crawl the user page and get the above attributes. 
I hope to contribute to you as a token of gratitude to the CP community :)

**Comment by aropan** [comment]
Activated.
