### ISSUE TITLE
about addition of algoleague.com

### ISSUE THREAD

**Issue by muratbiberoglu** [aropan/clist#409]
Hi, I hope you are doing ok!

We have a competitive programming site in Turkey which is [algoleague](https://algoleague.com/). algoleague has nearly 7 thousand users and it is nearly 3 years old (we have a contest for celebrating 3rd year soon). On average there are 2-3 contests per month.

We would like to add algoleague to your website. If it is ok for you, can you show us a guideline how to do so?

Thanks

**Comment by aropan** [comment]
Added https://clist.by/resource/algoleague.com/.
