### ISSUE TITLE
Standings - Weekly Contest 415 - No standings

### ISSUE THREAD

**Issue by manohar-poreddy-ispace-com** [aropan/clist#410]
Thanks for your work on clist, @aropan 

===

I think the previous problem has returned today

previous problem: https://github.com/aropan/clist/issues/333#issuecomment-2002279655

Cloudflare login related thing might have improved now

Can you share what you are doing as of today?
1 are you loggedin to leetcode during pull
2 wat headers u used
3 what is language
etc
a sample snippet can help here

share above details, even if you could fix this time, so i can check do same from my side to repro for this/next time

==

![image](https://github.com/user-attachments/assets/2287fbea-3491-411e-84f7-8eb3d7499ae6)

==

**Comment by aropan** [comment]
Fixed. This was my mistake.

**Comment by manohar-poreddy-ispace-com** [comment]
I created this from the office acc
Could you delete this issue? Thanks
