### ISSUE TITLE
Schedule Calendar Menu Appears at Top of Page, Inconvenient for Events Scrolled at Bottom

### ISSUE THREAD

**Issue by MiinaMagdy** [aropan/clist#412]
### Description:
When attempting to schedule an event from the bottom of the page using the "Schedule Calendar" icon, the platform selection menu opens at the top of the page. This requires scrolling up manually to select a platform (Google, Outlook, Yahoo), which is inconvenient and disrupts the user experience. Additionally, the page doesn't auto-scroll or focus on the menu when it opens.

---

### Steps to Reproduce:
1. Scroll down to an event listed towards the bottom of the page.
2. Click on the "Schedule Calendar" icon corresponding to that event.
3. Observe that the menu appears at the top of the page, while the user is still scrolled to the bottom.

---

### Expected Behavior:
The platform selection menu should appear near the "Schedule Calendar" icon that was clicked, or the page should automatically scroll up to the menu for easier access.

---

### Environment:
- Browser: Mozilla Firefox 131.0 & Brave v 1.70.117
- OS: Ubuntu 24.04.1 LTS
  
---

### Screenshots or Visuals:

![image](https://github.com/user-attachments/assets/c364586e-39ab-4706-ac61-3372ce775b74)
![image](https://github.com/user-attachments/assets/a096f104-869e-47dd-be9b-53d9bd97a487)

**Comment by aropan** [comment]
Fixed.

P. S. You could set default calendar for `Default import to calendar` on [preferences](https://clist.by/settings/preferences/) page to avoid open menu.
