### ISSUE TITLE
Add address card to list & other places

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#414]
Thanks for the work on clist, @aropan 

===

Please add Address card to list & other places where account is present

===

Address card on hover
![image](https://github.com/user-attachments/assets/f42cf08a-3ed5-4beb-b58d-e4fd3da78449)

List, etc
https://clist.by/list/a417ea34-3ddf-4fab-8802-8437626d23d3/

**Comment by aropan** [comment]
Added to list.

**Comment by manoharreddyporeddy** [comment]
@aropan 

because unable to see at https://clist.by/list/a417ea34-3ddf-4fab-8802-8437626d23d3/ 
Please check below may be its not deployed for cases, or if you can see please add a screenshot on how to see it

![image](https://github.com/user-attachments/assets/47fe3bac-baa2-4dd0-bb3d-187f6ee4289a)

===

I think, card shud be per person, like we see at https://clist.by/standings/54983229/?list=a417ea34-3ddf-4fab-8802-8437626d23d3&neighbors=on
![image](https://github.com/user-attachments/assets/e197cf43-7c6d-4224-9595-8b4250f2d698)

===

**Comment by aropan** [comment]
https://github.com/user-attachments/assets/a599ca92-19e0-4ad3-8d7a-f6bb6294adc8

**Comment by aropan** [comment]
Oh, I understand.

**Comment by manoharreddyporeddy** [comment]
Ya

![image](https://github.com/user-attachments/assets/5e702417-ef50-4fc0-97d8-731e6320d1d0)

**Comment by aropan** [comment]
Fixed.

**Comment by manoharreddyporeddy** [comment]
Working. Thank you

![image](https://github.com/user-attachments/assets/a61dfeb9-522e-4bd8-802a-943ca15abad2)
