### ISSUE TITLE
codingninjas.com rating

### ISSUE THREAD

**Issue by bugdone** [aropan/clist#416]
codingninjas added rating for weekly contests a while back
I see there's an [API call](https://www.naukri.com/code360/api/v3/public_section/user_rating_data?uuid=4b57941f-037b-4522-ab40-4fa877b386c3&naukri_request=true) for fetching rating

**Comment by aropan** [comment]
Done. https://clist.by/resource/naukri.com/code360/.
Accounts will be updated soon.
