### ISSUE TITLE
CLIST did not update some of the contests from the Yandex Cup

### ISSUE THREAD

**Issue by FFTotoro** [aropan/clist#418]
In this year's Yandex Cup, an additional [Yandex Cup 2024 - Algorithm - Semifinal - Juniors](https://contest.yandex.com/contest/70296/standings/) was introduced, featuring the same tasks as the [Yandex Cup 2024 - Algorithm - Semifinal](https://contest.yandex.com/contest/70295/standings/).

**Comment by aropan** [comment]
Added https://clist.by/standings/algorithm-semifinal-juniors-55535347/.

Yandex Cup don't have public information about juniors (start and end time) and standings url (and other contests also). But they did page with schedule https://contest.yandex.com/yacup/schedule. This is good.
