### ISSUE TITLE
I don't have access to the Luogu Tournament Calendar

### ISSUE THREAD

**Issue by Oracynx** [aropan/clist#422]
I don't have access to the Luogu Tournament Calendar

![image](https://github.com/user-attachments/assets/a5d3a3e1-3d7a-475d-9715-07fea92b05d4)

Translate: 

Translation of the yellow words in the upper left corner: Events from one or more calendars cannot be displayed here because you do not have permission to view them.

**Comment by CodingOIer** [comment]
it's ok now
