### ISSUE TITLE
Leetcode user id rename

### ISSUE THREAD

**Issue by anuragdw710** [aropan/clist#425]
I recently renamed my LeetCode user ID, but I'm unable to add the new ID without removing the old one.

If I add the new ID, will my previous data be lost that is associated with the old ID?

**Comment by aropan** [comment]
No need to delete. You could participate and after update your leetcode account will be renamed. I triggered it.

**Comment by anuragdw710** [comment]
I recently renamed my CodeChef account, but it seems to still recognize my old account as the primary one. It might be ordering accounts alphabetically. 
As a result, my profile displays the old account by default, with a '+' sign to view the other account. Additionally, the contest count is not updating to reflect the new account.
![image](https://github.com/user-attachments/assets/06bb7118-e8de-4511-91b5-2d2dd07b4a58)
![image](https://github.com/user-attachments/assets/805036cf-ab20-463a-99b5-57a7029cb14a)

**Comment by aropan** [comment]
Fixed. I added renaming account for codechef (was disabled). And reparsed and reupdate your main account. Thanks for report.
