### ISSUE TITLE
Standings - Lower score has higher rank

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#426]
Thanks for your work on clist @aropan 

===

Looks like some issue , lower score has higher rank
at https://clist.by/standings/biweekly-contest-145/?list=a417ea34-3ddf-4fab-8802-8437626d23d3

SS
![image](https://github.com/user-attachments/assets/2d7c9fdf-41b8-457a-b352-fd25e13129d2)

**Comment by manoharreddyporeddy** [comment]
Leetcode has same issue
May be, its a new rule system ( due to more bugs ) or bug
at https://leetcode.com/contest/biweekly-contest-145/ranking/465/

![image](https://github.com/user-attachments/assets/2420ee51-bd31-4cbc-b72b-fac329294178)

May we can wait and see for some time on this ticket.

**Comment by aropan** [comment]
Fixed by leetcode.
