### ISSUE TITLE
No standings for Weekly Contest 427

### ISSUE THREAD

**Issue by manoharreddyporeddy** [aropan/clist#427]
Thanks for your work on clist, @aropan 

===
There are no standings for today's contest of Weekly Contest 427
at https://clist.by/standings/weekly-contest-427/?list=a417ea34-3ddf-4fab-8802-8437626d23d3
which just completed at https://leetcode.com/contest/weekly-contest-427/ranking/

![image](https://github.com/user-attachments/assets/af16ac77-8257-43ad-9bb7-0efb67905653)

**Comment by aropan** [comment]
Fixed. The server space ran out - we need more ~gold~ space.
