### ISSUE TITLE
USACO Contests missing 

### ISSUE THREAD

**Issue by prabh1601** [aropan/clist#431]
I am not able to see usaco contests this year on the calendar

![image](https://github.com/user-attachments/assets/5a990f1c-da14-46c2-b6d3-0d2e8691841c)

**Comment by aropan** [comment]
Fixed.

**Comment by prabh1601** [comment]
They are missing again this year :p

<img width="263" height="347" alt="Image" src="https://github.com/user-attachments/assets/ec9f8a80-b36c-41db-b0a6-14dc6389fa0a" />

**Comment by aropan** [comment]
Fixed.
