### ISSUE TITLE
'Settings' object has no attribute 'PROBLEM_API_IGNORE_FIELD'

### ISSUE THREAD

**Issue by chinesedfan** [aropan/clist#432]
The latest [commit](https://github.com/aropan/clist/commit/fa42e17042eb293e4d95470910e15324850fb24f#diff-413cdd162f8ca0dc1968ac88a3af4e9d7bccabc7f0c685f53c135197c2f44330R356) breaks an API.

Sample Request:
https://clist.by:443/api/v4/statistics/?with_problems=true&contest_id__in=56248824&account_id=2276684

**Comment by aropan** [comment]
Fixed.
