### ISSUE TITLE
Search engines need to give more information

### ISSUE THREAD

**Issue by aropan** [aropan/clist#68]
**[Original report](https://bitbucket.org/aropan/clist/issue/68) by Aleksey Ropan (Bitbucket: [aropan](https://bitbucket.org/aropan), GitHub: [aropan](https://github.com/aropan)).**

----------------------------------------

**Comment by aayushbest** [comment]
I like to add more features to the existing the can show clist features like coders list , accounts and portal to show individual rating. It's better if Android application can be open source to make a contribution.

**Comment by aropan** [comment]
Basic information added.
