### ISSUE TITLE
Found this when open in firefox

### ISSUE THREAD

**Issue by Rahul365** [aropan/clist#87]
Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for www.clist.by. The certificate is only valid for the following names: clist.by, dev.clist.by, legacy.clist.by, netdata.clist.by
 
Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by VadVergasov** [comment]
In Google Chrome (80.0.3987.132) https://www.clist.by works well. 
[www.clist.by.zip](https://github.com/aropan/clist/files/4331418/www.clist.by.zip) Here is the certificate, I got from https://www.clist.by

**Comment by Rahul365** [comment]
I was using Mozilla firefox

**Comment by aropan** [comment]
Added redirect from www.clist.by to clist.by. Let me know if this does not help.

**Comment by Rahul365** [comment]
It worked
