### ISSUE TITLE
Handle

### ISSUE THREAD

**Issue by ivanovmp** [aropan/clist#90]
On the tab "Registration" I tried to specify my CF handle. I wrote `orz` in the corresponding field, but the system didn't allow to save this handle. Instead, it started to suggest me tons of various CF handles containing `orz` as substring. I scrolled down a lot, but wasn't able to find just `orz`, so I gave up and left the field empty.

I don't think it's how it's supposed to work. Maybe the suggestion part is redundant, and you could just believe that I enter the correct handle?

**Comment by aropan** [comment]
Maybe. But you can use regex `^orz$`.

**Comment by aropan** [comment]
Added select written handle.

**Comment by aropan** [comment]
And removed suggestion.
