### ISSUE TITLE
Fails to detect timezone in Japan

### ISSUE THREAD

**Issue by kmyk** [aropan/clist#92]
When I access https://clist.by at first time (or, in the new private window) from Japan (where uses Japan Standard Time +0900, `new Date().getTimezoneOffset() == -540`), it says `Warning! Timezone is set incorrectly. Please reload page.` and set the timezone as `+0800` incorrectly.

It seems `Asia/Choibalsan` is selected internally. The settings page of clist says `Asia/Choibalsan +9:00` but it actually +8:00 (https://www.zeitverschiebung.net/en/timezone/asia--choibalsan). I think this does something wrong.

**Comment by aropan** [comment]
for finding problem and PR. Updated.

**Comment by kmyk** [comment]
Thank you for updating! I get +0900 correctly!

**Comment by kmyk** [comment]
By the way, Daylight Saving Time (DST) may still cause issues for users in other countries.
It seems that `Asia/Chita` is used internally for +0900. Both of `Asia/Chita` and Japan Standard Time don't use DST, so it's OK for us now. But if `Asia/Chita` used DST, probably we would get a wrong time offset (e.g. +0930) only in summer. Please consider using values of `Date.getTimezoneOffset` directly, without mapping it to timezone names.
