### ISSUE TITLE
Crossed Out Scores

### ISSUE THREAD

**Issue by bqi343** [aropan/clist#95]
Why are some scores crossed out [here?](https://clist.by/standings/tco20-algorithm-stage-3-17680999/)

**Comment by aropan** [comment]
Some scores do not count to tie scores.

From rules https://tco20.topcoder.com/competition-overview/algorithm/algorithm-rules:
>...
> The highest total SRM scores accumulation including only those rounds in which all tied competitors participated.
> ...
