### ISSUE TITLE
Disconnect Old Telegram Chat

### ISSUE THREAD

**Issue by LumaKernel** [aropan/clist#96]
Hi, I'm glad to see this fantastic project at GitHub.

I had changed the Telegram account.
Old account was used to connect clist Bot.
Then I changed the account and tried accessing `https://clist.by/telegram/me` , but it just redirects me to `https://telegram.me/ClistBot?start` .
It seems that URL doesn't include information about finding my account, isn't ?

I took a quick look, not deeply, and think it needs a way to disconnect the old Telegram account and/or chat .

Thank you.

**Comment by aropan** [comment]
Do you have access to previous telegram account? I added `/quit` command to unlink account.

**Comment by LumaKernel** [comment]
Sorry, I can't. Lost the access...

**Comment by aropan** [comment]
Ok. Check https://clist.by/settings/social/. I added unlink tg and other services accounts.

**Comment by LumaKernel** [comment]
Gone well. I appreciate your works.
