### ISSUE TITLE
Allow API key reset.

### ISSUE THREAD

**Issue by aryanc403** [aropan/clist#97]
I couldn't find a way to resent API key. It seems API with each account is fixed. It would be helpful if one can reset his/her API key.

**Comment by aropan** [comment]
Added remove button on api page:

![image](https://user-images.githubusercontent.com/1968460/83930181-f678ba80-a79e-11ea-8424-4e03e79a9b21.png)

**Comment by aryanc403** [comment]
Thanks. This is exactly what I wanted.
